### ISSUE TITLE
Filtering by attributes

### ISSUE THREAD

**Issue by clarkezone** [renggli/dart-xml#102]
I'm having issues selecting nodes that have a particular attribute and there don't seem to be any examples of this.  I'm trying to do this:

        `var elems = flutterprojsearch
            .where((element) =>
                element.attributes.length >= 1 &&
                element.attributes.first.value == "flutterproject")
            .first;`

But no dice.

**Comment by clarkezone** [comment]
Alternative approach that also doesn't work:

`var elems = flutterprojsearch.where((element) =>
            element.attributes.where((aa) => aa.name == "Label").length == 1);`

**Comment by csells** [comment]
can you post a small repro, @clarkezone ?

**Comment by clarkezone** [comment]
> can you post a small repro, @clarkezone ?

Can do but can't get to it until this evening.

**Comment by clarkezone** [comment]
Programmer error.  Sorry for the noise.
