### ISSUE TITLE
This is a great package, but needs XPath!

### ISSUE THREAD

**Issue by RandalSchwartz** [renggli/dart-xml#103]
The other XPath pub packages don't provide as much diligence in parsing the XML, but this package is missing XPath, which would make it far more useful for parsing and traversing trees.  Any chance that's in the works?  I'm not willing to do all the work, but I could help you out if you needed.

**Comment by renggli** [comment]
I am not familiar with XPath. Personally I think it is more convenient to use plain Dart (including your preferred IDE, debugging tools, ...) to [traverse and query](https://github.com/renggli/dart-xml#traversing-and-querying) XML. That said, it should be easy make one of the existing XPath packages work on the DOM of this library?

**Comment by RandalSchwartz** [comment]
I think maybe I could come up with a petitparser XPath description, although there is some trickiness around namespaces and the built-in expressions.  I would also need help designing it so that the semantics of execution using the XML package's interface got wired up properly.

**Comment by renggli** [comment]
There will be some basic support for a subset of XPath with the upcoming version 7.0.0.

Documentation: https://github.com/renggli/dart-xml#xpath
Demo: https://petitparser.github.io/examples/xml/xml.html

Marking this as closed, please report missing features and bugs as new issues.

**Comment by RandalSchwartz** [comment]
Excellent, thank you!  Yeah, I've been following the progress.
