### ISSUE TITLE
Error thrown when parsing Doctype

### ISSUE THREAD

**Issue by scottste** [renggli/dart-xml#104]
Hello,

I get the following error when trying to parse a doctype: `XmlParserException (Closure: () => String from Function 'toString':.: Expected name at 2:4)`

I'm using version 5.1.0

Here is the xml:

```
  <?xml version="1.0"?>
  <!DOCTYPE TEI.2 PUBLIC "-//TEI P4//DTD Main DTD Driver File//EN" "http://www.tei-c.org/Guidelines/DTD/tei2.dtd"[
  <!ENTITY % TEI.XML "INCLUDE">
<!ENTITY % PersProse PUBLIC "-//Perseus P4//DTD Perseus Prose//EN" "http://www.perseus.tufts.edu/DTD/1.0/PersProse.dtd">
%PersProse;
]>
<TEI.2>
</TEI.2>
```

**Comment by renggli** [comment]
Thank you, I can reproduce the problem. This is also a very strange error message ... investigating.

**Comment by scottste** [comment]
Thank you so much!
