### ISSUE TITLE
Add more XmlElement getter functions

### ISSUE THREAD

**Issue by Robbendebiene** [renggli/dart-xml#106]
In JavaScript there exist always two kind of functions/getters. One for getting nodes (which include text nodes and elements) and one for elements only.

Currently there exist a lot of getters for returning nodes, but only a few getters for returning elements only (like `firstElementChild`). Getters like `children`, `nextSibling`, `previousSibling` are missing such an implementation.

Somehow related to: #43

Thanks for the great library.

**Comment by renggli** [comment]
Added a bunch of new helpers, please let me know if anything else is missing?

**Comment by Robbendebiene** [comment]
Thanks a lot!

I've checked the API and only found generator functions like `preceding`, `ancestors`, `descendants`, `following` that could benefit from such helpers.

**Comment by renggli** [comment]
I've published `xml 5.2.0` with these improvements.
