### ISSUE TITLE
builder.buildDocument() .toXmlString() returns null when called 2nd time ?

### ISSUE THREAD

**Issue by RageshAntony** [renggli/dart-xml#122]
After building a XML document , When calling builder.buildDocument().toXmlString() for first time , it returning the XML string 

But when calling for 2nd time directly without any changes , it returns null;

final xml1 = builder.buildDocument().toXmlString() // returns correct XML string
final xml2= builder.buildDocument().toXmlString() // returns Null !!

Why ?

**Comment by renggli** [comment]
Because building resets the builder so that you can build something new. If you write

```dart
final doc = builder.buildDocument();
final xml1 = doc.toXmlString();
final xml2 = doc.toXmlString();
```

this works as expected. I agree that could be documented better.

**Comment by RageshAntony** [comment]
> Because building resets the builder so that you can build something new. If you write
> 
> ```dart
> final doc = builder.buildDocument();
> final xml1 = doc.toXmlString();
> final xml2 = doc.toXmlString();
> ```
> 
> this works as expected. I agree that could be documented better.

Thanks . Working
