### ISSUE TITLE
"Phantom" XmlText nodes after parsing

### ISSUE THREAD

**Issue by JulianCologne** [renggli/dart-xml#130]
First of all: great package!

I'm quite new to working with xml files but one thing is really unexpected (see example below):

Test.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Comment here. -->
<Person>
	<Name>Peter</Name>
</Person>

```

I'm parsing the data which works fine
```dart
final doc = XmlDocument.parse(File('Test.xml').readAsStringSync());
```

But when I iterate over the children
```dart
doc.children.forEach((node) => print(node.nodeType));
```

I'm getting the following output:
```console
XmlNodeType.DECLARATION
XmlNodeType.TEXT                <<< why?
XmlNodeType.COMMENT
XmlNodeType.TEXT                <<< why?
XmlNodeType.ELEMENT
XmlNodeType.TEXT                <<< why?
```

I'm a little confused by that. Where do these xmlText nodes come from? Their text content contains only CR+LF.
I can get rid of the last one by removing the empty line in the end and one of the first ones by removing the comment but there will always be at least one XmlText node.
Is this normal / expected behaviour?

**Comment by renggli** [comment]
There is (whitespace) text between the declaration, comment and the first element. The library cannot know which whitespaces are relevant in your case, so it preserves them all.

If you don't care about whitespaces only text nodes it is easy to filter them away:

```dart
final childrenWithoutWhitespaceText = parentNode.children
    .where((node) => !(node is XmlText && node.text.trim().isEmpty));
```

**Comment by renggli** [comment]
Actually there is also [Node.normalize()](https://github.com/renggli/dart-xml/blob/fc6593a612eab992fe9a84f88ab675ff1bd08679/lib/src/xml/visitors/normalizer.dart#L12) that puts all child nodes into a "normalized" form, that is no text nodes in the sub-tree are empty and there are no adjacent text nodes.

So you don't care about any whitespace you could write:

```dart
final doc = XmlDocument.parse(File('Test.xml').readAsStringSync()).normalize();
```

**Comment by JulianCologne** [comment]
Thanks for the quick reply.

> There is (whitespace) text between the declaration, comment and the first element. The library cannot know which whitespaces are relevant in your case, so it preserves them all.

To be honest, I don't understand that. Why can't the library know that? If we assume valid XML then raw text at this position is impossible?! The library should be able to figure out where text is possible and otherwise not create an extra node? Please clarify, maybe I just don't understand xml properly / well enough yet :D

Is it perhaps optimized for handling/streaming very large files (1GB++) so that these checks cost too much performance?



> Actually there is also [Node.normalize()](https://github.com/renggli/dart-xml/blob/fc6593a612eab992fe9a84f88ab675ff1bd08679/lib/src/xml/visitors/normalizer.dart#L12) that puts all child nodes into a "normalized" form, that is no text nodes in the sub-tree are empty and there are no adjacent text nodes.
> 
> So you don't care about any whitespace you could write:
> 
> ```dart
> final doc = XmlDocument.parse(File('Test.xml').readAsStringSync()).normalize();
> ```

Thanks for the tip!
Unfortunately this did not work in my case. Maybe because the text nodes are not empty but contain CR+LF?
```dart
final doc = XmlDocument.parse(File('Test.xml').readAsStringSync());
doc.normalize();
```
The above gives me the same result as before.

**Comment by renggli** [comment]
The significance of whitespaces in XML is defined in the DTD or Schema. In the absence (of support) for those systems, the library has to consider all whitespaces as potentially significant. However, it lets you easily trim and remove them from the parsed document as you see fit in your use-case.

True, `normalize()` doesn't trim the whitespaces, but you can easily create your own transformation along the same idea. Possibly there could be an option to trim all text in the normalize function?

**Comment by JulianCologne** [comment]
thanks for all the quick answers and explanations!
I appreciate it very much!

I understand that whitespaces can't just be discarded.

What confused me is that whitespace and "real content" have the same type. Ex:

Data:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Comment here. -->
<Person>
	<Name>Peter</Name>
</Person>
```

Code:
```dart
final doc = XmlDocument.parse(File('Test.xml').readAsStringSync());
for (final descendant in doc.descendants) {
  print(descendant.nodeType);
  }
}
```

Output:
```console
XmlNodeType.DECLARATION
XmlNodeType.ATTRIBUTE
XmlNodeType.ATTRIBUTE
XmlNodeType.TEXT         <<< Whitespace
XmlNodeType.COMMENT
XmlNodeType.TEXT         <<< Whitespace
XmlNodeType.ELEMENT
XmlNodeType.TEXT         <<< Whitespace
XmlNodeType.ELEMENT
XmlNodeType.TEXT         <<< "Real content": Peter
XmlNodeType.TEXT         <<< Whitespace
```

Maybe it is possible to add another type (XmlWhitespace?) so you can differentiate between whitespace between elements and "real content" like this:
```console
XmlNodeType.DECLARATION
XmlNodeType.ATTRIBUTE
XmlNodeType.ATTRIBUTE
XmlNodeType.WHITESPACE 
XmlNodeType.COMMENT
XmlNodeType.WHITESPACE 
XmlNodeType.ELEMENT
XmlNodeType.WHITESPACE 
XmlNodeType.ELEMENT
XmlNodeType.TEXT         <<< the only "Real content" here is easy to spot
XmlNodeType.WHITESPACE
```

**Comment by renggli** [comment]
The node types are given by the XML standard (https://www.w3schools.com/xml/dom_nodetype.asp). It might be obvious for you what the relevant whitespace in your case are, but for the computer it is not.

Anyway, I've added some configuration options to the normalizer and you can ow specify a predicates to (selectively) trim and/or collapse whitespace:

```dart
doc.normalize(
  trimWhitespace: (textNode) => true,
  collapseWhitespace: (textNode) => true,
);
```

**Comment by JulianCologne** [comment]
Great, thanks for all the explanations and the effort!
