### ISSUE TITLE
Eliminate dynamic calls

### ISSUE THREAD

**Issue by srawlins** [renggli/dart-xml#131]
We've seen dynamic calls adding to binary size. Some come from this package.

These can be statically linted with avoid_dynamic_calls, and then removed.

**Comment by renggli** [comment]
We probably also have the fix this in https://github.com/renggli/dart-petitparser?

**Comment by srawlins** [comment]
There is plenty of `dynamic` in petitparser for sure, but not too much dynamic invocation. I do think I saw at least one instance in a recent trace, so I'll be filing a bug there.
