### ISSUE TITLE
attribute escaping character  '>'

### ISSUE THREAD

**Issue by Kandrasheu** [renggli/dart-xml#135]
In Canonical XML, all characters from the information set appearing in character data or attribute values are represented by their UTF-8 encoding, with the following exceptions:

In character data and attribute values, the characters "<" and "&" are represented by "&lt;" and "&amp;" respectively.
In character data, the character ">" is represented by "&gt;".

**Comment by Kandrasheu** [comment]
XmlEntityMapping

**Comment by Kandrasheu** [comment]
XmlDefaultEntityMapping handles "&<\n\r\t" but not ">"
While this can be worked around by using custom EntityMapping it should probably be handled in XmlDefaultEntityMapping

https://www.w3.org/TR/1999/WD-xml-c14n-19991109.html

**Comment by renggli** [comment]
I am not familiar with the "Canonical XML" that you reference. https://www.w3.org/TR/xml/#syntax says: _The right angle bracket (>) may be represented using the string " &gt; "_.
