### ISSUE TITLE
Upgrade petitparser dependency

### ISSUE THREAD

**Issue by clragon** [renggli/dart-xml#139]
I was interested in using `petitparser` to parse a custom html-like language from an API I digest, 
but I found that I cannot use the newest version, `5.0.0`, because a package I use, 
`flutter_native_splash` uses `dart-xml` and `dart-xml` depends on `petitparser 4.3.0`.

Since `flutter_native_splash` is only a dev dependency for generating the splash screen, I can ignore it for now (using a dependency override),
but it would be lovely if `dart-xml` could be upgraded to the latest `petitparser`, if thats possible.

**Comment by renggli** [comment]
Yeah, that should be possible. I am working on some improved on version 5.0.0 of dart-xml (with some breaking changes, but also a lot of performance improvements). In the meantime I can try to release an intermediate version that works with the latest version of petitparser.

**Comment by renggli** [comment]
Published https://pub.dev/packages/xml/versions/5.4.0
