### ISSUE TITLE
Access attributes in XmlNode using Map instead of List

### ISSUE THREAD

**Issue by mlesin** [renggli/dart-xml#14]
I think it would be much more convenient and faster (in terms of performance) to use something like this to access attribute on xmlNode:
```dart
element.attributes['attr1'].value
```
instead of:
```dart
element.attributes.firstWhere((XmlAttribute e)=>e.name.qualified=="attr1").value
```
Also this way would be much easier to detect attribute duplicates, which are not allowed in XML.

**Comment by renggli** [comment]
What about using

   element.getAttribute('attr1')

?

**Comment by mlesin** [comment]
Shame on me :)

ср, 3 Июн 2015, 21:53, Lukas Renggli <notifications@github.com>:
