### ISSUE TITLE
XmlDocument.parse accepts invalid documents in version 6

### ISSUE THREAD

**Issue by robert-ancell** [renggli/dart-xml#143]
Previously the following would throw `XmlParserException`, however in version 6 neither do.

```dart
XmlDocument.parse('');
XmlDocument.parse('foo');
```

Based on the [documentation](https://pub.dev/documentation/xml/latest/xml/XmlDocument/XmlDocument.parse.html) I would expect these to throw exceptions as the input is not valid XML.

**Comment by renggli** [comment]
Thanks for reporting, yeah that behavior got lost when transitioning to the stream-based parsing. I will look at adding the missing errors back (0 or more than 1 root elements).

**Comment by renggli** [comment]
Wondering if the DOM parser should also check the ordering of the declaration, doctype and root element (it currently doesn't)?

**Comment by robert-ancell** [comment]
Is it possible to make a release with this fix? I'd like to [update dbus.dart](https://github.com/canonical/dbus.dart/issues/341).

**Comment by swenhancer** [comment]
+1 for making a release with this fix.

**Comment by MattCCC** [comment]
Hello, thank you for a great plugin. Any possibility to publish 6.0.2?

**Comment by renggli** [comment]
I published [6.1.0](https://pub.dev/packages/xml/versions/6.1.0).
