### ISSUE TITLE
Parse attribute without value

### ISSUE THREAD

**Issue by CodeDoctorDE** [renggli/dart-xml#146]
I want to parse a html document but I get the error `Unhandled Exception: XmlParserException: ">" expected at 17:140`.
```xml
<script nonce="a" defer src="/core/js/oc.js?v=e23870b"></script>
```

**Comment by renggli** [comment]
`defer` is not a valid XML attribute.

Generally HTML documents cannot be parsed by an XML parser, as HTML has much more relaxed rules with regards to attributes and nesting/closing tags.

**Comment by CodeDoctorDE** [comment]
This is a pity. Do you have an alternative?
