### ISSUE TITLE
Gets attribute as expected, but throws StateError too

### ISSUE THREAD

**Issue by DavidBucienski** [renggli/dart-xml#147]
Using findElements() works as expected, unless element contains href attribute with query string attached to it. 
Like,  https:// example.com/example.jpg?aid=rss_feed

So for example, the following will throw StateError and still provide href as expected. It does both. 
`try {
      final itunesImageElement = itemElement.findElements('itunes:image').first;
      final itunesImageAttrib =
          itunesImageElement.getAttribute('href') ?? 'No itunesImage Attribute';
      itunesImage = itunesImageAttrib;
    } on StateError {
      print('StateError is thrown ');
    }`

However, if href attribute is  https:// example.com/example.jpg 
You still get href value as expected and no StateError is thrown.

**Comment by renggli** [comment]
Hard to tell what is going on. Can you paste the full stack trace of the `StateError`?

**Comment by DavidBucienski** [comment]
Here is stack trace:
I/flutter ( 7708): StateError is thrown
I/chatty  ( 7708): uid=10146(com.example.part1) 1.ui identical 7 lines
I/flutter ( 7708): StateError is thrown
I/flutter ( 7708): itunesImage | https://image.simplecastcdn.com/images/8862bce3-8814-46a6-9b72-a533960bbd50/5dd1869a-dac7-4edc-acb6-f791663f6fd1/3000x3000/wim176-frisby-ep-01-v001.jpg?aid=rss_feed

**Comment by DavidBucienski** [comment]
I just added a _finally_ after the StateError {} and it is showing in stack trace the expected itunesImage value. And then showing the initial value I declared in the begin of the factory. I have to create a minimal viable project for you that demos this behavior. Should have this for you within 24 hours.

**Comment by renggli** [comment]
I'd like to see where the full stack of where the `StateError` is thrown, not where it is handled :-)

**Comment by DavidBucienski** [comment]
I don't know how to do that. I took the time to make a MVP, it is 280MB, tried to paste it here and got file too big error. How do I get this to you?

**Comment by DavidBucienski** [comment]
Ok, just discovered `on StateError catch (e, s)` is this what you want?

I/flutter ( 7161): Unknown exceptions: Bad state: No element, with stack: 
I/flutter ( 7161): #0      Iterable.first (dart:core/iterable.dart:624:7)
I/flutter ( 7161): #1      new RssItem.parse (package:fake_throw/models/rss_item.dart:21:75)
I/flutter ( 7161): #2      new RssFeed.parse.<anonymous closure> (package:fake_throw/models/rss_feed.dart:26:43)
I/flutter ( 7161): #3      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
I/flutter ( 7161): #4      new List.from (dart:core-patch/array_patch.dart:41:17)
I/flutter ( 7161): #5      new RssFeed.parse (package:fake_throw/models/rss_feed.dart:24:17)
I/flutter ( 7161): #6      RssParser.loadAsset (package:fake_throw/services/rss_parser.dart:12:13)
I/flutter ( 7161): <asynchronous suspension>
I/flutter ( 7161): #7      RssFeedLogic.rssFeed (package:fake_throw/rss_feed_logic.dart:12:25)
I/flutter ( 7161): <asynchronous suspension>
I/chatty  ( 7161): uid=10146(com.example.fake_throw) 1.ui identical 7 lines
I/flutter ( 7161): Unknown exceptions: Bad state: No element, with stack: 
I/flutter ( 7161): #0      Iterable.first (dart:core/iterable.dart:624:7)
I/flutter ( 7161): #1      new RssItem.parse (package:fake_throw/models/rss_item.dart:21:75)
I/flutter ( 7161): #2      new RssFeed.parse.<anonymous closure> (package:fake_throw/models/rss_feed.dart:26:43)
I/flutter ( 7161): #3      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
I/flutter ( 7161): #4      new List.from (dart:core-patch/array_patch.dart:41:17)
I/flutter ( 7161): #5      new RssFeed.parse (package:fake_throw/models/rss_feed.dart:24:17)
I/flutter ( 7161): #6      RssParser.loadAsset (package:fake_throw/services/rss_parser.dart:12:13)
I/flutter ( 7161): <asynchronous suspension>
I/flutter ( 7161): #7      RssFeedLogic.rssFeed (package:fake_throw/rss_feed_logic.dart:12:25)
I/flutter ( 7161): <asynchronous suspension>

**Comment by renggli** [comment]
Yes, perfect: Looks like `RssItem.parse` calls `first` on an empty collection (package:fake_throw/models/rss_item.dart:21:75). Look for the bug there ...

**Comment by DavidBucienski** [comment]
Sorry for bothering you with this non-existent issue.
