### ISSUE TITLE
XmlElement.setAttribute can create duplicate attribute if the name contains a colon

### ISSUE THREAD

**Issue by andrewkolos** [renggli/dart-xml#156]
Appears to be new in 6.2.1.

[Issue repro repo](https://github.com/andrewkolos/xml_set_attribute_issue). Run the tests using both 6.2.0 and 6.2.1 to see a difference in results.

```dart
// passes in 6.2.0
// fails in 6.2.1
test('setting existing attribute that contains a colon in its name - should overwrite attribute', () {
  final bookshelfXml = '''<?xml version="1.0"?>
      <car color:name="blue">
      </car>''';
  final document = XmlDocument.parse(bookshelfXml);
  final carElement = document.rootElement;
  expect(carElement.getAttribute('color:name'), equals('blue'));
  // In 6.2.1, this creates another color:name
  // attribute instead of overwriting the existing one.
  carElement.setAttribute('color:name', 'red');
  expect(carElement.getAttribute('color:name'), equals('red'));
});
```

**Comment by renggli** [comment]
Thanks for the bug report, that looks indeed like an issue. Surprised this wasn't caught by existing tests :-/

**Comment by renggli** [comment]
Thanks again for reporting, added a bunch of more tests. 

Generally I am not happy with the way the library handles namespaces, it was added on top of it after the fact and there are various known problems (#136 and #64). I am looking into improving this, but unfortunately this means to make some API breaking changes ...

**Comment by renggli** [comment]
Updated the release to 6.2.2.
