### ISSUE TITLE
How to remove node from xml

### ISSUE THREAD

**Issue by salman731** [renggli/dart-xml#166]
I want to know that how to remove/delete specific node from xml.

**Comment by renggli** [comment]
For an attribute `attribute.parent?.attributes.remove(attribute)` and for everything else `node.parent?.children.remove(node)`.

Possibly could add a `remove()` method to `XmlHasParent` to simplify this slightly.

**Comment by salman731** [comment]
how to find node by tag name and delete/remove it.
