### ISSUE TITLE
How to omit xml declaration and remove indentation?

### ISSUE THREAD

**Issue by salman731** [renggli/dart-xml#167]
I want to know how I can omit xml declaration and remove indentation.

**Comment by renggli** [comment]
Did you work through [tutorial and documentation](https://pub.dev/documentation/xml/latest/)? Sometimes also the the [examples](https://github.com/renggli/dart-xml/tree/main/example) or to study the [code](https://github.com/renggli/dart-xml/tree/main/lib/src/xml) itself could be helpful?

**Comment by salman731** [comment]
I have seen through documentation but I did not find how to remove indentation but I find a way to omit xml declaration

**Comment by renggli** [comment]
Regarding removing indentation try `document.normalize(trimWhitespace: (text) => true)`, see [XmlNormalizerExtension.normalize](https://pub.dev/documentation/xml/latest/xml/XmlNormalizerExtension/normalize.html).
