### ISSUE TITLE
Parsing and reencoding document should be identical

### ISSUE THREAD

**Issue by daniel-v** [renggli/dart-xml#17]
Hello,

I ran into an issue where parsing an XML document and then calling `doc.toXmlString()` on it does not produce the same output (ignoring white space characters).

I created a GIST of it [here](https://gist.github.com/daniel-v/e6d016374474eb257cdb8f92f0606bbb), I think the test case details the issue quite well.

TL;DR:
if an XmlNode contains `&gt` it gets encoded when calling toXmlString().

Pointer: `XmlWriter.visitText`

**Request:** there should be a way to output an XML String in such a way that `XmlText` nodes' contents do not get encoded.

**Comment by renggli** [comment]
Thank you for the GIST allowing me to quickly reproduce the observed issue.

In your example, re-encoding creates a different output because ">" is valid XML text and doesn't normally need to be encoded.

Same problem exists in various other places where the XML nodes are unable to keep the exact source of the parsed input, e.g. the delimiter types of attributes, whitespace within elements, and whitespace at document level.

While it is technically possible to solve the reported and the various related problems, I am not sure if it is worth the trouble? Most XML libraries I know don't do it.

Would it help to be able to specify a custom encoder function?

**Comment by daniel-v** [comment]
Yes, allowing me to specify a custom encoding/decoding function will possibly solve this specific issue, however I am not entirely certain we are on the right track.

**Question:** is it a valid requirement that I should be able to retrieve textual contents of an XmlElement without any modification if it is valid XML - even if it contains such character sequences that are decodable?

I saw in a previous issue that you brought up PHP's implementation as reference. I created yet another [gist](https://gist.github.com/daniel-v/008e16b98e0b9484ff17f94c175a7f6a) (my PHP skills are terrible).

If the answer to the question is `yes`, the default behavior of this library should reflect it. Until such time arrives, I would be happy with the custom function you mentioned.

----

### My use-case

The following wall of text is only loosely related to the issue at hand; I wanted to offer you some context as to how I'd like to use this library.
I am using it to parse an XML based format, called [XLIFF](http://docs.oasis-open.org/xliff/xliff-core/xliff-core.html). 
A small snippet from an XLIFF file:
```xml
<trans-unit id="some_trans_unit_id" datatype="xml">
    <source><bpt ctype="x-g" equiv-text="[" id="_0">&lt;g id=&quot;_0&quot;&gt;</bpt>3. helyezett: </source>
</trans-unit>
```
From my application's point of view, it is crucial, that the contents of `source` can be retrieved as-is, without any kind of encoding/decoding.
If I retrieve the text contents of the source `sourceElement.text` I get `<g id="_0">3. helyezett:`. It was devised that such fragments be wrapped in `bpt` tags and encoded to produce valid XML.

**Comment by renggli** [comment]
With c2fb10dad2cd88f923ff8a1d6cf4d9fda37a4feb single and double quotes in attributes are preserved.

With b2482cdd6bc36193e950d49149ddb25272e7eaa0 whitespaces, processing instructions and comments at the document level are preserved.
