### ISSUE TITLE
How to convert xml to string without backslahes

### ISSUE THREAD

**Issue by salman731** [renggli/dart-xml#171]
I want to know that how to convert xml to string with backslashes, I tried doc.toString() and doc.toXmlString() but still with backslashes in evaluated variable in android studio.Basically I am encoding xml after query and transversing to utf8 and pass doc.toString() for utf8 encoding  then bytes are different from hardcoded xml string encoded with utf8.

![image](https://i.imgur.com/7gVdBG1.png)

**Comment by renggli** [comment]
Looks like your debugger is putting those backslashes, because there are double-quotes in a double-quoted string. The backslashes are not actually part of `toString()`.

**Comment by salman731** [comment]
After parsing, query and changing xml utf8 encoding changes but harcoded xml string it does not..
