### ISSUE TITLE
New release with XPath support?

### ISSUE THREAD

**Issue by sharpordie** [renggli/dart-xml#173]
Do you plan to release a new version soon? I tried installing from GitHub directly but there are issues with flutter_test.

Thank you very much for your impressive work. ;)

**Comment by renggli** [comment]
Thank you for your kind words. 

The goal was to have the XPath functionality part of the next major release of `xml 7.0.0`. This unfortunately depends on the next major release of `petitparser 6.0.0` which brings improvements in error reporting and parsing speed. However the internal code changes go pretty deep, so it breaks all dependencies that use internal infrastructure of PetitParser (implement custom parsers). Unfortunately there are quite a few on [pub.dev](https://pub.dev/) and I am kind of stuck.

A possibility would be to backport the XPath functionality to the last version that works with the currently release version of PetitParser, but this is a larger project ... (not really from the code point of view, more from the branch management).

**Comment by sharpordie** [comment]
Dependency hell... I had the idea to use a plugin to make XPath in Kotlin but it doesn't work with Isolate, so I'm stuck. Fortunately it's for a small personal project, I think I'll rewrite it in Kotlin and Swift because of its size. I hope however that it will get unstuck on your side. ;)
