### ISSUE TITLE
isSelfClosing not working

### ISSUE THREAD

**Issue by bubnenkoff** [renggli/dart-xml#174]
```
var xml = '''
      <segment name="NotifyAEC" alias="notifications">
            <segment name="London" alias="London"> </segment>
      </segment>
''';

void main(List<String> arguments) {
  final document = XmlDocument.parse(xml);
    var childrens = document.childElements;
   print('segment child: ${childrens.first.getAttribute('name')} isSelfClosing: ${childrens.first.isSelfClosing} ');
}
```

Output:
```
segment child: NotifyAEC isSelfClosing: true
```

but it should be false: because `<segment name="London" alias="London"> </segment>` have closing tag.

**Comment by renggli** [comment]
As [the comment](https://pub.dev/documentation/xml/latest/xml/XmlElement/isSelfClosing.html) on the filed says this is not representing what was read from the input, but _whether the element should be self-closing when empty_.

The original intent was that self-closing tags serialize the smallest and that if the all children get removed it should serialize in the shortest possible way. And normally it shouldn't matter how the tag is rendered.

Do you have pointers how other libraries handle this? What would be a better solution?

**Comment by bubnenkoff** [comment]
@renggli thanks for response, honestly I do not know about how it's done in another libs, but I need such future.
Could you implement it (I do not know how this properly could be designed)

**Comment by renggli** [comment]
Note, if you want to check for emptiness, you probably rather want to use `exampleElement.children.isEmpty`, because conceptually `<example-element />` and `<example-element></example-element>` are exactly the same and all other libraries I know can't event tell them apart.

**Comment by bubnenkoff** [comment]
@renggli only one question, does example from GPT mean that he understand docs like I am? (and we are both wrong)
