### ISSUE TITLE
XmlParserException: ">" expected at 1:16

### ISSUE THREAD

**Issue by mkbsugita** [renggli/dart-xml#175]
It can't be parsed.

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method PUT is not allowed for the URL /myURL.</p>
</body></html>
```

from S3 error

sorry. `myURL` is secret.

called by this
```
xml.XmlDocument.parse(response.body);
```

**Comment by renggli** [comment]
Note that your input is not valid XML, several online validators (https://www.w3schools.com/xml/xml_validator.asp, https://www.xmlvalidation.com/, https://www.liquid-technologies.com/online-xml-validator) agree with the library.

If this is HTML, you probably want to use a [HTML parser](https://pub.dev/packages/html) instead?

**Comment by mkbsugita** [comment]
Thank you for replying!

Amazon S3  reply such HTML...

Does your module check XML or HTML?
because, I want to check HTML or XML before parsing.

**Comment by renggli** [comment]
No, the input is expected to be valid XML. Typically XML documents start with `<?xml ...`, but that is not a requirement.
