### ISSUE TITLE
Parsing does not work starting with 6.2.2

### ISSUE THREAD

**Issue by kaciula** [renggli/dart-xml#178]
I used to be able to parse my xmls with this package until version 6.2.2 came around. Here is the type of xml that I am parsing. 

```
<P SC="NBJBE" SN="87871" PS="D25255" CN="S0981/2021" CC="35200141" OU="CAS-B" ID="2022-09-14" CT="CLN" A="false">
  <PD S="1" PT="PENS" ON="D25255" TY="E" CD="40139742746174368626" FN="IOAN" LN="PASCU" FA="Bucuresti, str. Romancierilor, nr. 2, bl. C4, sc. 4, ap. 62, judet BUCURESTI, sect. 6" CT="ROM" AC="false" MR="137" RO="1" IT="0" SX="1" BD="1957-01-04" FP="0" PP="0040749273726" PE="mihai1984@gmail.com" PA="Bucuresti, jud. BUCURESTI, sect. 6, str. Veteranilor, nr.11A, bl., et.1, ap."></PD>
  <D DC="573" DT="2" LT="B" LP="50" CN="1" BP="false" AS="ESOMEPRAZOLUM" C="40mg" PF="COMPR. GASTROREZ." D="1/zi" Q="30" TC="2" IT="0" M="" TD="30"></D>
</P>
```

And here is the code:

`final XmlDocument doc = XmlDocument.parse(input);`

It doesn't see the children or anything. It seems the childElements for the doc contains only one child which is the entire input.

I'm forced to use the latest version of this package because of a Flutter upgrade but it no longer works as it did before. Can you help?

**Comment by renggli** [comment]
I am not aware of a recent XML parsing change. When I parse your document and then inspect the resulting document with the following snippet:

```dart
for (var node in doc.descendantElements) {
  print('${'  ' * node.depth}${node.qualifiedName}: '
      '${node.attributes.length} attributes, '
      '${node.children.length} children');
}
```

I get the following output as expected:

```
  P: 9 attributes, 5 children
    PD: 19 attributes, 0 children
    D: 15 attributes, 0 children
```

Note that the node returned from the parser is `XmlDocument` with `P` as its sole child.

**Comment by kaciula** [comment]
Thanks for the response.

Indeed. I was looking for the P node comparing the node's name with a XmlName() object. It works on older versions but not on the new versions. I have now changed to directly compare the String names.

Thank you and sorry for taking up your time.

**Comment by renggli** [comment]
See the discussion here of why `XmlName.==` was removed: https://github.com/renggli/dart-xml/pull/153
