### ISSUE TITLE
Error: Type 'Result' not found.

### ISSUE THREAD

**Issue by yuhaya** [renggli/dart-xml#181]
`: Error: Type 'Result' not found.
iterator.dart:18
  Result<XmlEvent>? _context;
  ^^^^^^
: Error: Method not found: 'Failure'.
iterator.dart:13
        _context = Failure(input, 0, '');
                   ^^^^^^^
: Error: 'Result' isn't a type.
iterator.dart:18
  Result<XmlEvent>? _context;
  ^^^^^^
: Error: 'Success' isn't a type.
iterator.dart:29
      if (result is Success) {`

[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale zh-Hans-NO)
    • Flutter version 3.16.0 on channel stable at /Users/rustyu/Documents/flutter/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (5 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rustyu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • XRust (mobile)  • 00008101-000A39993A10001E • ios            • iOS 17.0.3 21A360
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
exit code 0

**Comment by renggli** [comment]
Thanks for the error report. Could you provide a snippet of code that reproduces the error, and include the package versions of the `xml` and `petitparser` you are using (by running `dart pub deps`).

**Comment by yuhaya** [comment]
> Update petitparser to the latest version and the problem no longer occurs.
