### ISSUE TITLE
The dart sdk version in pub.yaml should be a range?

### ISSUE THREAD

**Issue by Hilbert2048** [renggli/dart-xml#182]
```shell
Resolving dependencies...
The current Dart SDK version is 3.2.0-210.4.beta.

Because simple_icons depends on xml >=6.5.0 which requires SDK version ^3.2.0, version solving failed.
``` 

what about:
```dart
environment:
  sdk: ">=3.2.0 <4.0.0"
```

**Comment by renggli** [comment]
From a practical standpoint I am unable to test with older SDK versions. New releases are always published with the latest stable dependencies. Consider sticking with an older version of `simple_icons` until your dependencies have caught up; or using [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides). 

Note that the current stable version of the Dart SDK is 3.2.3.
