### ISSUE TITLE
.children property includes text nodes and comments

### ISSUE THREAD

**Issue by gibahjoe** [renggli/dart-xml#184]
In the JSDom parser and the HTML parser, the `.children` do not include Comments and text nodes. but this library does

find below sample code

``` dart
void main() {
  final xmlString = '''
  <root>
    <element1>Text</element1>
    <!-- Comment -->
    <element2>More Text</element2>
  </root>
  ''';

  final document = XmlDocument.parse(xmlString);
  final root = document.rootElement;

  print(root.nodes.length);      // returns 7
  print(root.children.length);   // returns 7
}
```

However, in JSDOm, there is a distinct difference between .children and .nodes

``` javascript
const xmlString = `
<root>
  <element1>Text</element1>
  <!-- Comment -->
  <element2>More Text</element2>
</root>
`;

const parser = new DOMParser();
const xmlDoc = parser.parseFromString(xmlString, 'application/xml');

const root = xmlDoc.documentElement;

console.log(root.childNodes);  // Includes text nodes and comment nodes
console.log(root.children);    // Only includes element1 and element2
```

Can this library be updated to reflect this? right now, there is no difference between `.children` and `.nodes` which makes either redundant.

**Comment by gibahjoe** [comment]
On further investigation, i can see this was a delibrate implementation

```dart
const Set<XmlNodeType> childrenNodeTypes = {
  XmlNodeType.CDATA,
  XmlNodeType.COMMENT,
  XmlNodeType.ELEMENT,
  XmlNodeType.PROCESSING,
  XmlNodeType.TEXT,
};
```

is there any reason why?

**Comment by renggli** [comment]
Note, this library is not a port of JSDom and does not attempt to provide a similar API.

- Use `node.attributes` to get the attributes of the node.
- Use `node.children` to get the children of the node (different nodes support different types, this is what the code you quoted above lists).
- Use `node.childElements` to get only the children of type `XmlElement`.
- Use `node.nodes` to get an `Iterable` over attributes and children of a node.

**Comment by gibahjoe** [comment]
I see. `.childElements` is what I was looking for. Thank you.

As an aside, I understand it is not a port. However,  I think unifying the API will be beneficial for adoption and ease of use especially with the dom parser api in the official dart HTML parser library.   `Node` for instance is almost identical to `XmlNode` if not identical but they are not interoperable.


Thanks once again.

**Comment by renggli** [comment]
I agree that the naming could be improved. However changing this now is rather expensive, because there are over 400 packages on [pub.dart.dev](https://pub.dev/packages?q=dependency%3Axml) that depend on this library; and likely many more applications that are not publicly visible.
