### ISSUE TITLE
Error: The specified language version is too high. The highest supported language version is 3.0.

### ISSUE THREAD

**Issue by aikakaliwang** [renggli/dart-xml#185]
xml-6.5.0/lib/xml.dart:1:1: 
Error: The specified language version is too high. The highest supported language version is 3.0.
/// Dart XML is a lightweight library for parsing, traversing, querying and

**Comment by renggli** [comment]
From a practical standpoint I am unable to test with older language versions. New releases of this package are always published with the latest stable SDK. Consider sticking with an older version of this package until you upgraded your development enviornment.
