### ISSUE TITLE
Minor var name change

### ISSUE THREAD

**Issue by lubi888** [renggli/dart-xml#20]
Hi Rengli,

I just tried to build and xml file and I had to change a variable name from the example. 

it's probably related to that little code we changed at the end of last week; that import namespace.

` builder.element('price', nest: 39.95);
  });
  builder.element('price', nest: 132.00);
});
var xml = builder.build();`

so i just changed the name of the var xml to xmlPrint
and then just called print.
`  builder.element('price', nest: 132.00);
});
var xml1 = builder.build();
   //have to change xml to anything otherwise, because of xml.xmlBuilder, gives 'Local variables cannot be referenced before they are declared'
print(xml1.toString());`

I need help with dart and xml but I'll throw it open to the general stackoverflow questions later as I want to learn some other mistakes i'm making with dart:io.

later,

**Comment by renggli** [comment]
Thank you for the bug report and detailed analysis. I fixed it in fb1471d7f6f496be75294634bccf8d8183f39179 as suggested.
