### ISSUE TITLE
Request for XmlBuilder.processing to include support for creating xslt and schema.

### ISSUE THREAD

**Issue by lubi888** [renggli/dart-xml#21]
Hi,

I'd like for XmlBuilder to have more features and include commands for working with .xsl and .xsd files. 

If i knew how to do it myself then I'd perform a pull request but I have a lot to learn with dart so perhaps some other programmers could help if they have the time. I will keep trying also.

I have a [stackoverflow](http://stackoverflow.com/questions/38951322/could-xmlbuilder-processing-accept-more-arguments) question about this. 

I'm just a little puzzled. I thought dart would have hit up against SGML before. Is everyone using JSON for accessing their db's through the server? 

I know some parts of xml got ugly with large config files but I like that it's extensible and both human and computer readable. I just think dart should have more Xml support overall. Xslt is an easy enough way to create Html pages from xml data and I think dart should have these programming tools on call.

sincerely,

lubi

**Comment by renggli** [comment]
XSLT and Schema support could be added as part of a separate library on top of this library. Possibly we could even ship it as a side-library in this package. I personally don't have the need for this functionality, but I am happy to discuss a design and merge a pull request.

**Comment by lubi888** [comment]
https://github.com/renggli
https://www.lukas-renggli.ch/
2019.03.11

Hi Lukas,

I don't know if i can help you with the dart xsl code necessary. 

I do like the idea of forking and writing of top of what you've put into dart xml.

I know everyone is using JSON as it is often shorter but I still like and want to have the option of XML and Turing Complete XSLT for dart and flutter. Sometimes I still find XML easier to read than JSON.

I can help with some links on what XML & XSL are supposed to do and how they are still very relevant for the web.

Perhaps ask some of the Flutter, even Fuschia, Google programmers and community for help and tips.

**_Official W3C links:_**
https://www.w3.org/Style/
https://www.w3.org/Style/XSL/
https://www.w3.org/standards/xml/
https://www.w3.org/standards/xml/transformation
https://www.w3.org/standards/techs/xslt#w3c_all

**_W3Schools links:_**
https://www.w3schools.com/xml/xml_xslt.asp
https://www.w3schools.com/xml/xsl_intro.asp
https://www.w3schools.com/xml/xpath_intro.asp
https://www.w3schools.com/xml/dom_intro.asp
https://www.w3schools.com/xml/schema_intro.asp

**_Golang help:_**
https://golang.org/pkg/encoding/xml/
Sadly, the support in Go is not that great either and there appears to be no XSLT packages.
https://github.com/antchfx/xpath
Some XPath support for Go.

**_Java help:_**
https://docs.oracle.com/javase/tutorial/jaxp/xslt/intro.html
http://www.java2s.com/Tutorials/Java/Java_XML/0200__Java_XSLT_Intro.htm

**_Dart ideas:_**
https://pub.dartlang.org/packages/xpath#-readme-tab-
Someone, R. Zhao, has tried XPath late last year 2018.09.

**_XML general help:_**
https://www.xml.com/     
The site was founded in 1996 by Textuality Services, O’Reilly Media, and the Seybold group.

https://en.wikipedia.org/wiki/XSLT
Wiki general help that is also in Deutsch, Francais and other languages.

http://www.unidex.com/turing/utm.htm
A turing test for XSLT. A lost of the turing tests are scholarly papers.

**Comment by lubi888** [comment]
Sorry Lucas, I may have closed this request too early. If I do end up writing some code to help then I'd like to have any input you might have.
If you want to close the issue then that's also OK. Otherwise, the request for dart xsl code is still open and I think your the man to get it done if you ever have the time.
