### ISSUE TITLE
namespace example and documentation

### ISSUE THREAD

**Issue by lubi888** [renggli/dart-xml#22]
Hi Renggli, guys,

Do you mind providing an example of adding a namespace if you have any spare time?

I'm trying to follow the constructors and data types but the code is still giving up errors. Could you post an example of adding a namespace with the bookshelf.xml builder or something like that?

What would be the correct use of namespace declaration for the whole document and then namespaces for individual elements and their attributes using the builder? 

```
builder.namespace(String uri, [String prefix])

builder.element(String name, {String namespace: null, Map<String, String> namespaces: const {, Map<String, String> attributes: const {}, dynamic nest: null}})
```

How would i add a namespace to an attribute?
`builder.attribute(String name, dynamic value, {String namespace})`

With the optimisenamespaces would it just be set to 'true'?
`builder.optimizeNamespaces
`

Any help or guidance you can offer would be appreciated. later

**Comment by renggli** [comment]
For working examples please see the tests. 

Here is an example defining a namespace and adding it to both, an element and an attribute: 

- https://github.com/renggli/dart-xml/blob/c2fb10dad2cd88f923ff8a1d6cf4d9fda37a4feb/test/xml_test.dart#L876.

Here are examples demonstrating the optimization of namespaces: 

- https://github.com/renggli/dart-xml/blob/c2fb10dad2cd88f923ff8a1d6cf4d9fda37a4feb/test/xml_test.dart#L942,
- https://github.com/renggli/dart-xml/blob/c2fb10dad2cd88f923ff8a1d6cf4d9fda37a4feb/test/xml_test.dart#L971,
- https://github.com/renggli/dart-xml/blob/c2fb10dad2cd88f923ff8a1d6cf4d9fda37a4feb/test/xml_test.dart#L991

I'll see, if I can put one of the examples into the tutorial.

**Comment by lubi888** [comment]
goodmorning, rengli. 

this is great and will keep me going today. the namespaces will help with both xml and xslt creation. once I have that it's simple to create html quickly. 

thanks a bunch and I'll talk to you later.

**Comment by lubi888** [comment]
Hi renggli,

it was the 

`}, namespace: uri);`

that I was after. i had worked out the builder.namespace('http/xyz', 'xyz'); but couldn't add it to the element root as a prefix until this morning in your xml_test.dart. Line 876 with namespace binding was what I needed to affix the prefix...

```
test('namespace binding', () {
      var uri = 'http://www.w3.org/2001/XMLSchema';
      var builder = new XmlBuilder();
      builder.element('schema', nest: () {
        builder.namespace(uri, 'xsd');
        builder.attribute('lang', 'en', namespace: uri);
        builder.element('element', namespace: uri);
      }, namespace: uri);
      var xml = builder.build();
      assertTreeInvariants(xml);
      var actual = xml.toString();
      var expected =
          '<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsd:lang="en">'
          '<xsd:element />'
          '</xsd:schema>';
      expect(actual, expected);
    });
```

getting the prefix down was a little important to me because xslt can then use processing commands on top of them.  like  
`xsl:for-each`

last night i was able to get something like an xslt command with this

```
builder.element('xsl:for-each', nest: () {
    builder.attribute('select', 'x/y/z');
});
```

and that gave me a basic xslt loop

`<xsl:for-each select="x/y/z" />`

today, because of the namespace help, i can use this to get the 'xsl' (or whatever) prefix that i wanted with and extensible language. this opens up access to xslt and xpath functions
```
var uri = 'http://xsl';
builder.element('for-each', nest: () {
	builder.namespace(uri, 'xsl');
    builder.attribute('select', 'x/y/z');
}, namespace: uri);
```

that gives and output that looks the same but it has the namespace separate.

`<xsl:for-each xmlns:xsl="http://xsl" select='x/y/z" />`

later

**Comment by lubi888** [comment]
Hi Rengli,

Good start to the week? 

I think i've figured out most of the namespace info that I needed from the test files. Thanks for that.

There's one small thing; the test files use the old command without importing the dart-xml package as xml. Thus, if i copy code from the test into a new file it won't fly. I know the answer because you informed me a few weeks ago. Perhaps it doesn't need to be changed since all the tests have worked for me from the CLI.

```
import 'package:xml/xml.dart';
var doc = parse(bookshelfXml);
```

```
import 'package:xml/xml.dart' as xml;
var document = xml.parse(bookshelfXml);
```

later,

**Comment by renggli** [comment]
Thank you for the update.

Regarding the import: both ways of importing a library are common, it depends on your needs and what other libraries you are using (see https://www.dartlang.org/guides/language/language-tour#specifying-a-library-prefix for details).

**Comment by lubi888** [comment]
ok. thanks for everything, renggli.
