### ISSUE TITLE
Request for Flutter XML integration serialization

### ISSUE THREAD

**Issue by lubi888** [renggli/dart-xml#36]
Hi Rengli,

I don't know what you're working on but has anyone from the Flutter team asked you to take a look at XML serialization? Like [Flutter/JSON](https://flutter.io/json/).

I know everyone is using JSON now  because it's often shorter and faster to transmit but I like XML because its both human and [machine readable](https://en.wikipedia.org/wiki/Machine-readable_data).

I have not raised this on the main  [flutter/issues](https://github.com/flutter/flutter/issues) page. I'm sure you're in a better place than I am to converse with the flutter guys about this possible feature addition to the flutter framework.

Tschüss

**Comment by renggli** [comment]
I am sure one could create `xml_serializable` over [dart-xml](https://github.com/renggli/dart-xml), very similar to of how [json_serializable](https://github.com/dart-lang/json_serializable) was created over `dart:convert`.

Personally I don't have the time or interest to create such a package at the moment, but I am happy to assist should you discover any missing parts or problems in [dart-xml](https://github.com/renggli/dart-xml).
