### ISSUE TITLE
Feature Request : Support XML validation via DTD

### ISSUE THREAD

**Issue by Rockvole** [renggli/dart-xml#39]
Your library is very good, but validating XML via DTD is needed.

**Comment by renggli** [comment]
Validating XML is a large project that I don't have a personal need for. Happy to discuss a design and merge a pull request if somebody wants to work on this.

**Comment by nohkumado** [comment]
Hitting that milestone myself :D ready to help, but at least ATM the prospect of parsing the dtd, me alone....

**Comment by renggli** [comment]
With https://github.com/renggli/dart-xml/commit/81055546e67e766dbf8f6f2e2062d7161ba19d41 this might become an easier project.
