### ISSUE TITLE
Support dart 2.0

### ISSUE THREAD

**Issue by qichuan** [renggli/dart-xml#40]
I am getting the following error when using this library with dart 2.0

```
type 'List<dynamic>' is not a subtype of type 'Iterable<XmlNode>' in type cast where
  List is from dart:core
  Iterable is from
```

This error is thrown from `XmlGrammarDefinition` and it is probably to do with the sound type system in Dart 2.0

**Comment by renggli** [comment]
Thank you for the report. This is a duplicate of https://github.com/renggli/dart-xml/issues/38. Please make sure to update to at least `xml 3.0.0`, which is the first Dart 2.0 compatible version.
