### ISSUE TITLE
XML parsing in Flutter returns a text node '\n' between every element!

### ISSUE THREAD

**Issue by fatherchill** [renggli/dart-xml#43]
When parsing any XML in Flutter dart-xml is parsing the line breaks between elements as individual elements. This means that it is impossible to iterate through a list of nodes without 50% being filtered out. Additionally, the length of children (should be 2 not 3) and descendants (should be  12-13 not 27) is wrong. 

I'm running the latest Flutter, Dart 2.0 and dart-xml 3.0.0.

My code:
```
      var bookshelfXml = '''<?xml version="1.0"?>
    <bookshelf>
      <book>
        <title lang="english">Growing a Language</title>
        <price>29.99</price>
      </book>
      `<book>`
        <title lang="english">Learning XML</title>
        <price>39.95</price>
      </book>
      <price>132.00</price>
    </bookshelf>''';
      print ('Bookshelf Children');
      print (xml.parse(bookshelfXml).children.length);
      print (xml.parse(bookshelfXml).children);
      print ('Bookshelf Descendants');
      print (xml.parse(bookshelfXml).descendants.length);
      print (xml.parse(bookshelfXml).descendants);

```
```
Printout on console:
`I/flutter ( 2838): Bookshelf Children
I/flutter ( 2838): 3
I/flutter ( 2838): [<?xml version="1.0"?>, 
I/flutter ( 2838):     , <bookshelf>
I/flutter ( 2838):       <book>
I/flutter ( 2838):         <title lang="english">Growing a Language</title>
I/flutter ( 2838):         <price>29.99</price>
I/flutter ( 2838):       </book>
I/flutter ( 2838):       <book>
I/flutter ( 2838):         <title lang="english">Learning XML</title>
I/flutter ( 2838):         <price>39.95</price>
I/flutter ( 2838):       </book>
I/flutter ( 2838):       <price>132.00</price>
I/flutter ( 2838):     </bookshelf>]
I/flutter ( 2838): Bookshelf Descendants
I/flutter ( 2838): 27
I/flutter ( 2838): (<?xml version="1.0"?>, 
I/flutter ( 2838):     , <bookshelf>
I/flutter ( 2838):       <book>
I/flutter ( 2838):         <title lang="english">Growing a Language</title>
I/flutter ( 2838):         <price>29.99</price>
I/flutter ( 2838):       </book>
I/flutter ( 2838):       <book>
I/flutter ( 2838):         <title lang="english">Learning XML</title>
I/flutter ( 2838):         <price>39.95</price>
I/flutter ( 2838):       </book>
I/flutter ( 2838):       <price>132.00</price>
I/flutter ( 2838):     </bookshelf>, ..., 132.00, 
I/flutter ( 2838):     )`
```

pubspec.lock:

packages:
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.31.1"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.2"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  barback:
    dependency: transitive
    description:
      name: barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.2+15"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2+1"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.6"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2+1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  front_end:
    dependency: transitive
    description:
      name: front_end
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0-alpha.9"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.5"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.3"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+16"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2+1"
  isolate:
    dependency: transitive
    description:
      name: isolate
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1"
  kernel:
    dependency: transitive
    description:
      name: kernel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0-alpha.9"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.1+4"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6"
  multi_server_socket:
    dependency: transitive
    description:
      name: multi_server_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  node_preamble:
    dependency: transitive
    description:
      name: node_preamble
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  package_resolver:
    dependency: transitive
    description:
      name: package_resolver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.1"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.6"
  plugin:
    dependency: transitive
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0+2"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.4"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.6"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.29.0+1"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.2"
  shelf_packages_handler:
    dependency: transitive
    description:
      name: shelf_packages_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  shelf_static:
    dependency: transitive
    description:
      name: shelf_static
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.7"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.2"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_map_stack_trace:
    dependency: transitive
    description:
      name: source_map_stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.4"
  source_maps:
    dependency: transitive
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.4"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.2"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.4"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  test:
    dependency: transitive
    description:
      name: test
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.34"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.5"
  utf:
    dependency: transitive
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+4"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+7"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.7"
  xml:
    dependency: "direct main"
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.13"
sdks:
  dart: ">=2.0.0-dev.28.0 <=2.0.0-edge.af1436931b93e755d38223c487d33a0a1f5eadf5"

**Comment by renggli** [comment]
I think this is working as intended.

The parser has no and should not have knowledge about what whitespaces are meaningful to the user of the XML document. Dropping whitespaces would would leave us with a different document, and would prevent us from serialising back the tree to an identical string.

That said, it should be trivial to write a transformer that drops whitespaces between nodes. Have a look at https://github.com/renggli/dart-xml/blob/master/lib/xml/visitors/normalizer.dart, which does something similar (remove empty or consecutive text nodes).

**Comment by deakjahn** [comment]
It's unfortunate that the link went away and even more unfortunate that this isn't mentioned directly in the README. :-) While I can see your point in the round-trip argument, is very many cases we want to process the XML, not round-trip it. And those extra text nodes do cause a lot of trouble. So, either this should be built-into the parser (optionally, of course), or you should provide a clear example of how to achieve this very common task.

**Comment by deakjahn** [comment]
Well, not really a good solution. I used a copy of your `XmlNormalizer`, with the difference that it calls an `isWhitespace` extension instead of `isEmpty` to examine the text nodes. Whilte the parsing itself is fast enough to be hard to time, the trimming operation takes about 10 seconds or more (around 100,000 nodes in total) in my Android emulator. Clearly not a viable solution.

**Comment by renggli** [comment]
Yeah, the normalizer is optimized for a different use-case. In your case you want to create a new subclass to `XmlTransformer` and transform all calls to `node.children.map(visit)` with `normalize(node.children)` where:

```dart
List<XmlNode> normalize(List<XmlNode> children) => children
   .map((node) => node is XmlText ? XmlText(node.text.trim()) : node)
   .where((node) => node is! XmlText || node.trim().isNotEmpty)
   .map(visit);
```

That said, you probably want to pre-process and normalize your files on a more powerful machine than a Phone. Or alternatively use the streaming API, where you can do such transformations without instantiating so many nodes all at once.

**Comment by deakjahn** [comment]
I contemplated the stream approach for some time but, actually, my case is very simple, I have a non-hierarchical, single large list of XmlNodes, so the simples solution is to filter them to a new list using

          .rootElement
          .children
          .where((e) => e.nodeType == XmlNodeType.ELEMENT)
          .toList();

I don't even need to retain the original root element and structure, just the list of nodes.

Well, I don't know. Today's phones as often just as capable as desktop machines, if not more. :-)

**Comment by renggli** [comment]
I don't think the problem is the speed of the device, I am more concerned about 100,000 nodes that can take up a couple of GB of memory easily (also depending on the data inside).

Your project sounds like a typical case for the stream processes. The code below basically uses no memory and calls the forEach-callback with each sub-tree one-by-one:

```dart
await stream
    .toXmlEvents()
    .normalizeEvents()
    .selectSubtreeEvents((value) => value.name == 'book')
    .toXmlNodes()
    .forEach((node) => print(node));
```

See the tutorial for more complete examples.

**Comment by deakjahn** [comment]
OK, I'll try this one.

The number of items is relatively large but the whole XML is less than 4 MB, so I don't expect any issues.

**Comment by deakjahn** [comment]
The UTF8 decoder can no longer be called in a chain like

    stream.transform(utf8.decode)...

but, since Flutter 1.8.something:

  utf8.decoder.bind(stream)

Small difference but then the stream won't be turned into a `Stream<String>` so `toXmlEvents()` cannot be applied. It can be circumvented with extra copying but do you have a suggestion for the best practice to consume the stream if it comes from a byte buffer (maybe after decompressing-decrypting-whatever) instead of a string?

**Comment by renggli** [comment]
I am not sure why this is not possible in Flutter, it is even an example in the [latest documentation](https://api.dart.dev/stable/2.10.1/dart-convert/dart-convert-library.html).

**Comment by deakjahn** [comment]
It looks rather strange. I received an error message, Googled it and found this: https://groups.google.com/g/flutter-announce/c/LTe4SYU8-0Q

**Comment by deakjahn** [comment]
![Screenshot 2020-10-11 163136](https://user-images.githubusercontent.com/2234271/95681316-611f8400-0bdf-11eb-9e09-cf5eec5b91dd.png)

**Comment by deakjahn** [comment]
![Screenshot 2020-10-11 163449](https://user-images.githubusercontent.com/2234271/95681364-b3f93b80-0bdf-11eb-950f-7197ba17e24c.png)

**Comment by renggli** [comment]
Looks like the input stream is not correctly typed? In you example `Stream.fromIterable([xml])` is a `Stream<List<String>>` (that is already utf8), but it should be `String<Uint8List>`.

**Comment by deakjahn** [comment]
Merely a different error message, I'm afraid: "The argument type 'Utf8Decoder' can't be assigned to the parameter type 'StreamTransformer<Stream<Uint8List>, dynamic>'."

**Comment by renggli** [comment]
How do you get the input stream? What is its type?

**Comment by deakjahn** [comment]
I have the file in the assets, I can read it into a buffer:

    final data = await rootBundle.load(asset);

and I can turn it into a Stream:

    final stream = Stream.fromIterable([data.buffer.asUint8List()]);

my final goal would be to use the stream with three transforms fused: a decryptor, a decompressor and then utf8, to pass it to your parser and get the original XML as comfortably as possible. I can make it work with all steps copying to a new `UintList8` or `String`, so it does work, only that it doesn't look optimal that way.

**Comment by renggli** [comment]
What happens if you change `Stream` (which is equivalent to `Stream<dynamic>`) in the above example to `Stream<List<int>>`? Alternatively a `.cast<List<int>>()` before the `.transform(utf8.decode)` might also help.

**Comment by deakjahn** [comment]
It seems to move into the right direction (actually, I normally only use `final` but I wanted to make it more visible for you here :-) ).

`.toXmlNodes()toList()` at the end of the chain starts to show fragments of my original XML all right, all I need now is to find out how to assemble them again into my data list.

**Comment by deakjahn** [comment]
It works now, thanks. You may want to include that stream call into the README, though. :-)

**Comment by deakjahn** [comment]
Just to mention the end result quickly because, I think, there is something you could also profit from. :-)

In this particular case, I finally went with my own XML parser. It's a fixed file, I know there are no CDATA elements, I know the maximum size of the node values, I only use a very small set of entitites, only a maximum of one attribute for each node, and actually, I even use a non-standard XML in the end, omitting the root node, just a list of its children, end no empty tags at all, so I could make quite a few assumptions and cut corners. That's not really important for you, of course, but in the process of crafting it, I stumbled upon two issues that you could use to significantly speed up the parsing in the package. Just to give a rough estimate, my whole final parsing takes around one fifth of the original time and while I didn't take detailed measurements of the two issues I want to mention, I expect you could gain a factor of two or three in your package, too.

The first one is `utf8.decoder`. This one invariable creates a string (meaning allocation and copying) and you parse that string later. I really didn't like this approach. Because I wanted to base all my parsing on the underlying byte data, I integrated utf8 decoding into my lexer directly (interestingly, I stumbled upon the same table driven approach Flutter decided to use). This is one thing you could consider doing, using a modified event decoder that operates on a byte conversion sink instead of a string.

The second one is directly related to it. Not only you need to create a full string of the whole XML before you even start working on it, you do the chunk conversion using `str.substring()` and even concatenation with the leftover carry that involves repeated copying again. As I read directly from the byte buffer with my lexer, those parts are removed. And, interestingly, another modification even gave me another twofold increase in speed: I don't use the -- supposedly performant -- `StringBuffer` and more but created my own simplistic `StringBuilder` instead. The former keeps strings that are joined at the end, mine uses an integer list of the codeunits and simply returns the resulting string.

I can send you the relevant source code, of course, if you're interested. Rather simple. While the hand crafted special XML parser wouldn't be very useful to you, you might be able to use some of the other ideas.

**Comment by renggli** [comment]
Note that both the UTF8 encoding/decoding of Dart and the XML package are working on chunked streams, which neither allocates nor requires the complete string at any point in time. However, your example code allocates and awaits the conversion of the complete data, i.e. `await rootBundle.load(asset)`, `Stream.fromIterable([data.buffer.asUint8List()])` and `await utf8.decodeStream(stream)`.
