### ISSUE TITLE
Add XmlDocument attributes as Map

### ISSUE THREAD

**Issue by charafau** [renggli/dart-xml#46]
Hi! After working with xml I thought that it would be nice if XmlDocument had method like `mapAttributes` or `attributesAsMap()` which would simply return `Map<String, String>` where `key` would be attribute name and `value` would be attribute value. Which is one line change it's easy to add so I think I can add that if you accept PR and are fine with this idea.

**Comment by renggli** [comment]
Thank you for your suggestion. I see various ambiguities with providing such a generic map. For example it is not clear to me how it should deal with namespaces, how it should handle duplicated attribute names, how the order of attributes can be preserved, or what should happen when the user updates the map?

**Comment by charafau** [comment]
thanks for quick answer. I was thinking that it would return attributes for current document root so for example:
```xml
<note id="1" name="my note">
  <to id="sender">Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

if our root would be `note` then map would return `{'id': '1' , 'name': 'my note'}` but later if we change root to `to` then returned map would be `{'id', 'sender'}`.

Map should of course be `unmodifiable` . 

I don't think that order of attributes matters since the main purpose for this (at least for me) would be ability to get attributes values like this:

```dart
var id = attributesMap['id'] // id = '1'
```

**Comment by renggli** [comment]
I think the creation of the map you describe is rather specific. Other users might expect or need a different mapping.  To do lookups like you describe you can use `String getAttribute(String name, {String namespace})`. Otherwise I suggest you create a helper external to this library that creates the exact `Map` you need.
