### ISSUE TITLE
.findAllElements doesn't keep order?

### ISSUE THREAD

**Issue by goodis0** [renggli/dart-xml#47]
Hey, I'm receiving an XML with multiple items, each slightly different.  I am grabbing the name from each and building a list for the user to select from.  But the list generates in a random order each time making it so that I can't use the index.  Is there another way of doing this? 

So if i run:
doc.findAllElements.elementAt(0);

I get different responses, and I would like to get the same item everytime.

**Comment by renggli** [comment]
Strange, this should not happen and I cannot reproduce. I am happy to investigate further if you can provide a working example or better yet a test case as a pull request.

The order in which `findAllElements` is returning elements is in document order and as a lazy computed `Iterable`. If you access individual elements of the `Iterable` you should probably convert it to a list first?

**Comment by goodis0** [comment]
Your comment made me 2nd guess my XML Document, and that is indeed the problem, its being sent in a different order each time. fml sorry for the inconvience.

**Comment by renggli** [comment]
I've improved the documentation in eca3ba4f6caae2ed1391dc80dbd2a2803d0b6f63 to make laziness and document-order more explicit.
