### ISSUE TITLE
Get tag name of node

### ISSUE THREAD

**Issue by danielRi** [renggli/dart-xml#48]
I want to parse XML with many different node names, I have no possibility to get the tag name of a node: e.G.:

`<tagname>value</tagname>` 

AFAIK I have can get the `value` with `node.text`, but I can´t get the `<tagname>`. Am I doing something wrong or can this feature be added?

**Comment by renggli** [comment]
To get the fully qualified name call `node.name.qualified`.

To extract nodes with a specific name across all your document, you might want to use `document. findAllElements('tagname').forEach((node) => ...)`.

**Comment by MrDeeKey** [comment]
xml.XmlDocument document = xml.parse(XML_STRING);
xml.XmlNode node = document.rootElement.firstChild.nextSibling;
String name = (node as xml.XmlElement).name.toString();

**Comment by azmasamy** [comment]
@renggli 
I can't find node.name
was it deprecated?
How to find the tag now?
Also, what is the best way to extract all the tag names from an XML document?

**Comment by renggli** [comment]
Nodes don't have names, only Elements. It is defined here: https://github.com/renggli/dart-xml/blob/0d43fd274c8f24c961eefbf72394d4989256b9a1/lib/src/xml/nodes/element.dart#L31

**Comment by azmasamy** [comment]
So how can I get the tag names from an XML document? or the tag names of the ancestors of a node?

**Comment by renggli** [comment]
`document.descendants.whereType<XmlElement>().map((element) => element.name)`. Please consider reading the [tutorial](https://github.com/renggli/dart-xml#tutorial).

**Comment by azmasamy** [comment]
Hmmm, unfortunately, this didn't do what I expected. I have read the tutorial and it doesn't mention anything about what an XmlElement is.

I used Iterables to get the strings from an XmlNode and used substring to get the names of the tag then added the unique tag names to a list:

`      for (var tag in item.descendants) {
        if (tag.toString().contains('>')) {
          String tagName = tag.toString().substring(1, tag.toString().indexOf('>'));
          if(!tagNames.contains(tagName)) {
            tagNames.add(tagName);
          }
        }
      }` 
      
Please, inform me if there is a better way to do it.

**Comment by renggli** [comment]
Please study the [XML basics](https://en.wikipedia.org/wiki/XML#Key_terminology) and the [class documentation](https://pub.dev/documentation/xml/latest/). I would write it like `item.descendants.whereType<XmlElement>().map((element) => element.name.qualified).toSet()`.

**Comment by ellemenno** [comment]
i found my way here after being confused that if i have an `XmlElement` (which has `name`) and ask for its children, i get a list of `XmlNode`, which do _not_ have `name`.

eventually i realized `XmlElement` offers both `.children` &rarr; `XmlNodeList<XmlNode>` _**and**_ `.childElements` &rarr; `Iterable<XmlElement>`.

..so then it was a simple change from:

```dart
for (final XmlNode child in parentElement.children) {
  print('tag name: ??');
}
```

to:

```dart
for (final XmlElement child in parentElement.childElements) {
  print('tag name: ${child.name}');
}
```

it does seem a bit obvious in hindsight. and sure enough, once i knew what to look for, the documentation references it:

> There are convenience helpers to filter by element nodes only: `childElements`, [...]

..but i was confused long enough to search and find this issue 😉, so i hope this might save the next person a few minutes.
