### ISSUE TITLE
HELP: BUILD and POS xml with Flutter Example

### ISSUE THREAD

**Issue by NTMS2017** [renggli/dart-xml#51]
Hi,

Thanks for xml plugin. I made a small app for example. Please update **https://pub.dartlang.org/packages/xml**

I mange to build xml in Flutter and be able to post and get the response. Here is the code:

DEPENDENCIES:
```
// Add pubspec.yaml:   xml: "^3.2.1"
import 'package:xml/xml.dart' as xml;
import 'dart:io';
```

BUILD XML:
```
// TODO: BUILD XML FILE
Future<HttpClientResponse> _sendOTP() async {
  var builder = new xml.XmlBuilder();
  builder.processing('xml', 'version="1.0" encoding="iso-8859-9"');
  builder.element('MainmsgBody', nest: () {
    builder.element('UserName', nest: “xxxxxxxx”);
    builder.element('PassWord', nest: “yyyyyyyy”);
    builder.element('Action', nest: 5);
    builder.element('Mesgbody', nest: “I am Fluttering with Dart”);
    builder.element('Numbers', nest: 5);
  });
  var bookshelfXml = builder.build();
  String _uriMsj = bookshelfXml.toString();
  print("_uriMsj: $_uriMsj");

  String _uri = "https://*******.******.com/http****”;
  var _responseOtp = postOTP(_uri, _uriMsj);
  print("_responseOtp: $_responseOtp");
}
```

POST XML:
```
 // TODO: POST XML FILE
Future<String> postOTP(String _uri, String _message) async {
  HttpClient client = new HttpClient();
  HttpClientRequest request = await client.postUrl(Uri.parse(_uri));
  request.write(_message);
  HttpClientResponse response = await request.close();
  StringBuffer _buffer = new StringBuffer();
  await for(String a in await response.transform(utf8.decoder)) {
    _buffer.write(a);
  }
  print("_buffer.toString: ${_buffer.toString()}");
  return _buffer.toString();
}
```

**Comment by renggli** [comment]
Thank you for your feedback. What exactly would you like me to update?

**Comment by NTMS2017** [comment]
The overall score shows 48 and their suggestions is to maintain the example. If you can make a small example read write xml via http (https) I think overall score will be much higher than current one. I would like to help to keep such a perfect plugin score to be on top. :)

**Comment by renggli** [comment]
Ahh, interesting. I didn't realize the score was so low. Not sure, if this is just about the missing example though? I'll see what I can do ...

**Comment by NTMS2017** [comment]
Such a wonderful plugin and such a low score :( hope you can improve the score. Thanks

**Comment by renggli** [comment]
I've added an example, but the score didn't change. Looks to me like this is a bug on pub.dartlang.org. I've filed a bug against them: https://github.com/dart-lang/pub-dartlang-dart/issues/1659.

**Comment by NTMS2017** [comment]
Thanks, renggli

They analysed this package (today) on Sep 27, 2018, and I guess they are working on suggestions. Now there is no suggestions for the plugin...

**Comment by renggli** [comment]
Thanks for the help, back at a score of 98:

<img width="400" alt="xml-score" src="https://user-images.githubusercontent.com/131610/46162362-fef0c200-c255-11e8-89a9-42c567120ce4.png">
