### ISSUE TITLE
Add nodeName property into the XmlNode Class

### ISSUE THREAD

**Issue by WHATHELWHATHELWHATHEL** [renggli/dart-xml#52]
I have used this lib to make a simple BFS of a xml tree.
```

import 'package:xml/xml.dart' as xml;

void bfsTree(xml.XmlDocument node, callback) {
  final stack = [];
  stack.add(node);
  var index = 0;
  while(stack.isNotEmpty) {
    index += 1;
    final xml.XmlNode popped = stack.removeLast();
    callback(popped.toString(), index);
    if (popped.children.isNotEmpty) {
      stack.addAll(popped.children);
    }
  }
}


void main() {
  final String bookshelfXml = '''<bookshelf>
      <book>
        <title lang="english">Growing a Language</title>
        <price>29.99</price>
      </book>
      <book>
        <title lang="english">Learning XML</title>
        <price>39.95</price>
      </book>
      <price>132.00</price>
    </bookshelf>''';
  final xml.XmlDocument document = xml.parse(bookshelfXml.trim());
  bfsTree(
    document, 
    (resultString, index) { print('travse number $index this $resultString'); },
  );
}

```

I have tried to print out the name of every node I have traversed, then I realized that I have no way to access a XmlNode's node name except  turning the node into a string and extract the name from it.

Would you pleased add an `nodeName`  property to the XmlNode class ?  For those anonymous nodes like the Text node, you can simply assign something like `AnonymousText`  to it.

**Comment by renggli** [comment]
An `XmlNode` does not have a name, only an `XmlElement` (or `XmlAttribute`) node does. Check for that type and extract the name from the accessor:

    if (node is XmlElement) {
      print(node.name.qualified);
    }
