### ISSUE TITLE
3.2.4 is a breaking change and should have been 4.0.0

### ISSUE THREAD

**Issue by zoechi** [renggli/dart-xml#53]
https://github.com/renggli/dart-xml/commit/53d70947933bcf423a6ed58488f8663f78104d69#r31871569

**Comment by marcmorente** [comment]
When I try to generate the apk release with the command "flutter build apk", the console generates the following error:

Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.0/lib/xml.dart:43:25: Error: Method not found: 'ParserError'.
    throw ArgumentError(ParserError(result).toString());
                        ^^^^^^^^^^^
Compiler terminated unexpectedly.
Gradle task 'assembleRelease'... Done                       36,1s
Gradle task assembleRelease failed with exit code 1

I tried in pubspec.yaml: 

`dependencies:
  xml: '>=2.0.0 <=3.2.0'`
then
`dependencies:
  xml: '>=2.0.0 <=3.2.1'`
then
`dependencies:
  xml: '>=2.0.0 <=3.2.2'`
then
`dependencies:
  xml: '>=2.0.0 <=3.2.3'`

and I get the same error

**Comment by renggli** [comment]
Sorry about that. I didn't think anybody would call the constructor directly, I'll publish a fix shortly.

**Comment by marcmorente** [comment]
When I try to generate the apk release with the command "flutter build apk", the console generates the following error:

Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.0/lib/xml.dart:43:25: Error: Method not found: 'ParserError'.
throw ArgumentError(ParserError(result).toString());
^^^^^^^^^^^
Compiler terminated unexpectedly.
Gradle task 'assembleRelease'... Done 36,1s
Gradle task assembleRelease failed with exit code 1

I tried in pubspec.yaml:

dependencies: xml: '>=2.0.0 <=3.2.0'
then
dependencies: xml: '>=2.0.0 <=3.2.1'
then
dependencies: xml: '>=2.0.0 <=3.2.2'
then
dependencies: xml: '>=2.0.0 <=3.2.3'

and I get the same error

**Comment by renggli** [comment]
I published 3.2.5 (76fc15713ffe7edcb60e55e95e42e083b93e0951), I hope this fixes all problems?

**Comment by zoechi** [comment]
Great, thanks! Quick response keeps the problem small :) (hopefully)

**Comment by zoechi** [comment]
@marcmorente can you please try again without the `xml: ...` dependency in `pubspec.yaml`?
`flutter packages upgrade` `flutter build apk`

**Comment by marcmorente** [comment]
Thanks for solving the problem so quickly, while it was solved, I had found a temporary solution, and was to change the bitmap_font.dart file (which was the one that was failing) with the  merge -> https://github.com/brendan-duncan/image/pull/90.

But running `flutter packages upgrade flutter build apk` also solved the problem. Thank you !

**Comment by zoechi** [comment]
Thanks everyone!
I assume this can be closed then.

**Comment by MarkOSullivan94** [comment]
Thanks for resolving this! Think this issue was because of the 3.2.4 change - https://github.com/fluttercommunity/flutter_launcher_icons/issues/74
