### ISSUE TITLE
XmlEventAttribute is missing namespace

### ISSUE THREAD

**Issue by dnfield** [renggli/dart-xml#54]
Attributes can be in a specific namespace - the API doesn't support this currently.

**Comment by dnfield** [comment]
Actually, it looks like this is the case for XmlEventStartElement too... the `name` should probably be an `XmlName` instead of a string.

**Comment by renggli** [comment]
True, I had it like that in my initial attempt where I reused the normal DOM nodes. The problem with `XmlName` is with all the other DOM objects that many things simply don't work outside of that space (ownership navigation, namespace resolution, ...).

To keep events lightweight it would probably be the simplest to add separate accessors for the local name, the qualified name (what is currently returned), and the namespace prefix?

**Comment by renggli** [comment]
If this is ok, I can make a new release with e6c0458a2cd4097cd52222aff8ef5680b0d380d0?

**Comment by renggli** [comment]
I've released this as 3.3.1 on pub.
