### ISSUE TITLE
Add name property in XMLNode object

### ISSUE THREAD

**Issue by foureyez** [renggli/dart-xml#56]
I have a functionality to read only "firstName","age" children of a XMLElement("metadata").
```
<metadata>
    <firstName>test</firstName>
    <lastName>user</lastName>
    <age>20</age>
    <gender>M</gender>
</metadata>
```

As there is no such property "name" on XMLNode, it is not convenient to extract name from the XMLNode string.

Can "name" property be added to XMLNode object.
Is this a feature to be implemented or a design decision?
If intentional, then please suggest alternative way to do this apart from string manipulation.

**Comment by renggli** [comment]
What you would expect the `XmlNode` to return as a name, most nodes don't have names. 

If I understand your question correctly you could use `findElements` that lets you extract the age from the `metadataElement` quite easily:

 ```dart
var age = metadataElement.findElements('age')
    .map((element) => int.tryParse(element.text))
    .first
```

**Comment by foureyez** [comment]
Ok, I understand, what i was trying to do was iterate all the children of metadataElement and then check which one is "age" and read its value.
I thought the each child (node) here can have name as the value of the XML tag
Closing this.
Thanks
