### ISSUE TITLE
  Is it possible to support DBCS encoding like GBK？

### ISSUE THREAD

**Issue by whitestarlau** [renggli/dart-xml#58]
Maybe I used this plugin in wrong way,but if I want to use an XML file encoded by dbcs, such as gbk, the program will go wrong. With the help of gbk2utf8, it can run normally.
  Is it possible to support DBCS encoding like GBK in future？

**Comment by renggli** [comment]
The user of this library needs to provide all strings using UTF-16 encoded strings (like all standard Dart `String` instances). If your input is encoded differently, you need to transform it yourself. The XML library does not know the encoding you are using.

**Comment by whitestarlau** [comment]
so the library will ignore the info like `encoding="GB2312"`,user should handled this by themself.I got it,thanks for your reply.

**Comment by renggli** [comment]
Correct, this declaration is not used by the library itself. I've added a note to the parse method: 63b5e112d4d73dbeb4a81672413e471e224bff62.
