### ISSUE TITLE
Version solving failed for xml 3.4.0 and 3.5.0

### ISSUE THREAD

**Issue by tekno0ryder** [renggli/dart-xml#59]
Hi,

I am getting version solving failed when trying to install the package version 3.4.0 or 3.5.0,

```
> flutter packages get
> Running "flutter packages get"..                  
> The current Dart SDK version is 2.3.0-dev.0.5.flutter-a1668566e5.
> 
> 
> 
> Because wp_client depends on xml >=3.5.0 which requires SDK version >=2.3.0 <3.0.0, version solving failed.
> pub get failed (1)
> exit code 1
```

Running flutter -version: 

`Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (5 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)`

My pubspec.yaml

`environment:
  sdk: ">=2.2.2 <3.0.0"`

**Comment by renggli** [comment]
If I don't misread the error message, then this is a problem of the `wp_client` library. It should not depend on `xml 3.5`, if it wants to be compatible with Flutter. `xml 3.4.1` should be compatible with the current Flutter releases.

**Comment by tekno0ryder** [comment]
> If I don't misread the error message, then this is a problem of the `wp_client` library. It should not depend on `xml 3.5`, if it wants to be compatible with Flutter. `xml 3.4.1` should be compatible with the current Flutter releases.

wp_client is actually my app name,

I tested again and xml 3.4.0 and xml 3.4.1 does work, only xml 3.5.0 gives the error although my dart tools  meets the requirements `The current Dart SDK version is 2.3.0-dev.0.5.flutter-a1668566e5.`

**Comment by renggli** [comment]
I don't think you meet the requirement for `xml 3.5.0`, because `2.3.0-dev.0.5.flutter-a1668566e5 < 2.3.0`. Glad to hear that `xml 3.4` works for you.
