### ISSUE TITLE
Throw a FormatException when parsing fails

### ISSUE THREAD

**Issue by nex3** [renggli/dart-xml#62]
Currently, when parsing fails, it throws an `XmlParserException` which is not a subclass of [`FormatException`](https://api.dartlang.org/stable/dart-core/FormatException-class.html). This is contrary to the typical Dart exception style, in which `FormatException` is used for all format- or parser-related errors.

Ideally, it would even be a [`SourceSpanFormatException`](https://pub.dev/documentation/source_span/latest/source_span/SourceSpanFormatException-class.html), which provides a direct reference to the source location of the error and has a high-tech `toString()`.

**Comment by renggli** [comment]
Thank you for pointing out. Unfortunately [source_span](https://pub.dev/packages/source_span) does not match the current design very well and will be tricky to adopt without breaking existing code. The [source_span](https://pub.dev/packages/source_span) package is newer than both the underlying parsing infrastructure and the XML package.

As a first step make the `ParserException` implement `FormatException` in the underlying parsing infrastructure: https://github.com/petitparser/dart-petitparser/commit/afc9a82a3d4c164a5220af73422e2f00aea83f4b

**Comment by renggli** [comment]
Made `XmlParserException` implement `FormatException` in 1fc7866.
