### ISSUE TITLE
Type XmlOwned.parent as XmlParent

### ISSUE THREAD

**Issue by nex3** [renggli/dart-xml#63]
Since presumably there's no situation where an `XmlOwned.parent` node *won't* be a parent, it seems like `XmlParent` should be the return type of that getter.

**Comment by renggli** [comment]
Thank you for your feedback (also #62). I will look at both issues in a week or two, I am currently away from home with limited access to a computer.

**Comment by renggli** [comment]
Unfortunately this is not the case for `XmlAttribute` nodes, which are not a subclass of `XmlParent`, because they are `attributes` and not `children`. Please reopen if you have a suggestion on how to improve the class hierarchy ...

**Comment by nex3** [comment]
At the very least, using the term "parent" for both cases seems very misleading. Could you rename the getter to `owner`?

You could also add an `XmlChild` interface that's a subclass of `XmlOwned` for classes that are guaranteed to have an `XmlParent` owner, and adds specificity to the `parent` getter.

**Comment by renggli** [comment]
Initial attempt: caeb23f1c2c670b4148e3e6e249fb23725a1c866

**Comment by renggli** [comment]
I've cleaned up the DOM hierarchy to avoid the naming confusion. Also I've added in 7bbfbb3 a specific accessor `parentElement`, which makes it easier to access the parent element.

**Comment by nex3** [comment]
Can you post on this issue when these changes get released? Thanks!
