### ISSUE TITLE
3.6.0 isn't backwards compatible with 3.5.0

### ISSUE THREAD

**Issue by spebbe** [renggli/dart-xml#66]
Hi and thanks for `dart-xml`!

`pub global activate junitreport` currently fails because 3.6.0 breaks backwards compatibility (in this case, constructor for `XmlPrettyWriter`) although it was released using a semver minor bump.

Easy to work around by avoiding `pub global` and instead constraining dev_dependency versions, but thought I'd mention.

**Comment by renggli** [comment]
Thank you for reporting and sorry about breaking your package. I knew the constructor was publicly exposed, but didn't expect any users. The more common `toXmlString()` method should be backward compatible. I will submit a fix tonight and release 3.6.1.

**Comment by spebbe** [comment]
Great! No rush -- it's not my package, but we use `junitreport` in our CI/CD pipeline. I actually prefer it now that we don't use `pub global activate`, so it's all good.

**Comment by renggli** [comment]
Looking at the problem, I'd actually prefer to fix `junitreport`. I've submitted a pull request on their side: https://github.com/TOPdesk/dart-junitreport/pull/16

**Comment by spebbe** [comment]
Awesome -- thanks! Feel free to close.
