### ISSUE TITLE
XML parse with sub-tags

### ISSUE THREAD

**Issue by FilipeOS** [renggli/dart-xml#71]
Hi there,

I need an advise please.

Basically I'm parsing a xml file using this plugins:
```
  xml: ^3.5.0
  http: ^0.12.0+2
```

and the xml have inside tags for persons and inside that person it have a sub-tag with multiple categories and I have no idea how to embed and can't find information about it.
```
<Reader>
    <Name>Gabriella</Name>
    <Description>this is a description</Description>
    <Status>Available</Status>
    <Pin>78575</Pin>
    <Picture>
        http://xxx.com/blabla.jpg
    </Picture>
    <Categories>
        <Category name="Tools">
            <Skill>Sand</Skill>
            <Skill>Rock</Skill>
        </Category>
        <Category name="Languages">
            <Skill>English</Skill>
            <Skill>German</Skill>
        </Category>
    </Categories>
</Reader>
```

I'm using this bit of code:
```
http.Response response = await http.get(readers_feed);

      List<ReaderModel> _listReader = [];
      var parser = xml.parse(response.body);
      parser.findAllElements('Reader').forEach((node) {
        ReaderModel _readerModel;
        String readerPin = node.findElements('Pin').first.text;

        if (readerPin.isNotEmpty) {
          _readerModel = ReaderModel(
              readerPin: readerPin,
              readerName: node.findElements('Name').first.text,
              readerDescription: node.findElements('Description').first.text,
              readerStatus: node.findElements('Status').first.text);

          _listReader.add(_readerModel);
        }
      });
```

Can you advise please? Thank you

**Comment by renggli** [comment]
Could you please post a minimal runnable example that demonstrates the problem? Did you check the [documentation](https://github.com/renggli/dart-xml#traversing-and-querying) about how to traverse and extract data from a document? It is not clear to me what is your question ...

Some comments on the code:

- `xml.parse(response.body)` returns an `XmlDocument`, not a parser.
- The example input does not have a tag `<Pin>`, so the line `node.findElements('Pin').first` will always throw an exception.
-

**Comment by FilipeOS** [comment]
@renggli sorry, Pin exist, I just removed from example to be shorter, Pin is plain text like Name and Description.

My code above works, it's getting the .xml content and assigning to variables, I just don't know how to get sub-tags like "Categories" by "Tools" or "Languages".

**Comment by renggli** [comment]
Check the examples in the [documentation](https://github.com/renggli/dart-xml#traversing-and-querying) I linked.

Given the `<Reader>` tag as `node` you could extract the language skills as:

```dart
var languages = node.findAllElements('Category')
   .where((node) => node.attributeNamed('name') == 'Languages')
   .flatMap((category) => category.findElements('Skill'))
   .map((skill) => skill.text);
```

**Comment by FilipeOS** [comment]
One last question, I get this when I get the xml, it's because I don't have the xml header, how can I force to read has xml?

`Invalid argument(s): Unsupported scheme ''`

**Comment by renggli** [comment]
This has nothing to do with the xml library: It looks like `response.body` cannot correctly decode your response to a `String`, presumably because the response does include an invalid or no content-type header. The (BOM)[https://en.wikipedia.org/wiki/Byte_order_mark] prefix indicates `response.body` should have performed an UTF-8 decoding.

**Comment by FilipeOS** [comment]
I fixed that with a substring. thanks

About the code you provided from the categories:
```
var languages = node
              .findAllElements('Category')
              .where((node) => node.attributeNamed('name') == 'Languages')
              .flatMap((category) => category.findElements('Skill'))
              .map((skill) => skill.text);
```
I get:
```
I/flutter (17336): NoSuchMethodError: Class 'WhereIterable<XmlElement>' has no instance method 'flatMap'.
I/flutter (17336): Receiver: Instance of 'WhereIterable<XmlElement>'
I/flutter (17336): Tried calling: flatMap(Closure: (dynamic) => dynamic)
```

**Comment by renggli** [comment]
I've fixed various typos in the code in the meantime, I was typing this on the phone.

**Comment by FilipeOS** [comment]
Hi @renggli 

`I/flutter (20730): type '(dynamic) => dynamic' is not a subtype of type '(XmlElement) => Iterable<dynamic>' of 'f'`

**Comment by renggli** [comment]
I don't know, this has nothing to do with the XML library, this must be some error in the way you use the Iterables.
