### ISSUE TITLE
Because every version of flutter_test from sdk depends on xml 3.5.0 and ntms_cep depends on xml ^3.7.0, flutter_test from sdk is forbidden.

### ISSUE THREAD

**Issue by NTMS2017** [renggli/dart-xml#72]
I am keep getting this error.

My question is which version of xml plugin I have to use?

I am using Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287 and my flutter doctor shows as:

flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-CY)
    • Flutter version 1.12.13+hotfix.9 at /Users/**********/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/**********/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] Connected device (1 available)
    • SM G935F • ce12160c0d86152e01 • android-arm64 • Android 8.0.0 (API 26)

**Comment by renggli** [comment]
Please report to the respective package owners (`flutter_test` and `ntms_cep`) to update to the latest version of the xml package. I don't see anything I can do here ...
