### ISSUE TITLE
findElements and findAllElements no longer in 4.0.0+

### ISSUE THREAD

**Issue by tonyclickspace** [renggli/dart-xml#73]
Breaking change from v3 to v4 - the methods `findElements` and `findAllElements` are gone, with no replacement. Both methods are still mentioned in the readme.

Not sure if this is a documentation issue or missing code in the v4 refactor.

**Comment by renggli** [comment]
They are still there, you might need to adopt your imports if you selectively import the library: https://github.com/renggli/dart-xml/blob/master/lib/src/xml/navigation/find.dart
