### ISSUE TITLE
Parsing <dict> object - key & value pair 

### ISSUE THREAD

**Issue by d3xt3r2909** [renggli/dart-xml#74]
One question, because I don't see that this is possible right now in this lib. (btw. thanks for lib and good maintaining) 

I have XML like this: 

```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
  <dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>1</string>
    <key>SomeKey2</key>
    <string>3</string>
  </dict>
</plist>
```

Is it possible and how to get/change the value for `CFBundleDevelopmentRegion` key?

**Comment by renggli** [comment]
There are many ways to do this, see the documentation on [traversing and querying](https://github.com/renggli/dart-xml#traversing-and-querying).

One way would be:

```dart
  final document = parse(input);
  final keyNode = document
      .findAllElements('key')
      .firstWhere((element) => element.text == 'CFBundleDevelopmentRegion');
  final valueNode = keyNode.following.whereType<XmlElement>().first;
  valueNode.children
    ..clear()
    ..add(XmlText('Some other value'));
  print(document);
```

**Comment by d3xt3r2909** [comment]
@renggli  

Super, thanks for the quick reply and solution!
