### ISSUE TITLE
Getting a child using the bracket operator

### ISSUE THREAD

**Issue by ali2236** [renggli/dart-xml#75]
Hi.
I would like to suggest a feature:
getting the first child with the matching tag name using the [bracket] operator.

Example:
```dart
var document = parse(xml);
var bookshelf = document['bookshelf'];
var book = bookshelf.findElements('book').first;
var price = book['price'];
var title= book['title'];
```
This will make xml serialization way easier.

Another example:
```xml
<scaffold backgroundColor="ff707070">
    <appbar>
        <title>
            <text textStyle:fontFamily="OpenSans">Xml Page</text>
        </title>
    </appbar>
    <body>
        <listView>
        <text>and another one</text>
        <html style="h2 { color: black; }">
            <h2>This page is parsed from xml</h2>
            <img src="https://i.picsum.photos/id/363/200/300.jpg"/>
            <p>This part of the layout is in html</p>
        </html>
        </listView>
    </body>
</scaffold>
```
Dart parser:
```dart
  Widget xmlWidgetParser(document){
      var scaffold = document['scaffold'];
      if(scaffold==null) throw 'exception';
      var backgroundColor = scaffold.attributes['backgroundColor'];
      var appbar = scaffold['appbar'];
      return Scaffold(
        backgroundColor: backgroundColor!=null ? Color(backgroundColor) : null,
        appBar: appbar!=null ? parseAppBarXml(appbar) : null,
        body: scaffold['body']!=null ? parseXmlElementBody(scaffold['body']) : Container(),
      );
  }
```

**Comment by renggli** [comment]
I think this would be a rather ambiguous API. For example it is not obvious what to return if there are duplicates. Also this is inconsistent with the accessors `List<XmlAttribute> get attributes` and `List<XmlNode> get children` that are indexed in a sequential numeric fashion.

If this makes you API more convenient I suggest that you add a static extension similar to those for attributes: `String getAttribute(String name, {String namespace})`. I might consider adding this to the core library, but I am not convinced yet that this is generally useful.

**Comment by ali2236** [comment]
My suggestion is to start using the bracket operator to make working with this library more fun.

All I want is this:
```dart
extension on XmlNode {
  XmlElement operator[](String name) => this.findElements(name).first;
}
```
This implementation is good because the iterator stops after finding the first matching element.

Why should this be added:
- Does not override or break anything
- It return one element which is what bracket operators should do. for example list[2] returns one object or map['key'] only returns one value
- It makes makes using this package more fun. for example the bookshelf example can be parse like this:
```dart
  var document = parse(xml);
  var bookshelf = document['bookshelf'];
  var books = bookshelf
      .findElements('book')
      .map((e) => Book(e['title'].text, e['price'].text));
  var totalPrice = bookshelf['price'].text;
```

Why shouldn't be added:
- can't use namespaces

**Comment by ali2236** [comment]
`getElement(name)` does the job. it may be better to not use additional operators because a lot of big packages depend on this package and they might be using the bracket operator for something else.
well, I'm happy now 😁.

**Comment by renggli** [comment]
Glad you are happy; and thank you for the suggestion! The method might not be as concise as the operator, but I hope it still makes the use of the library more fun.

I have a bunch of other improvements in the pipeline, then I will release a new version ...
