### ISSUE TITLE
There is no convenient way to get the first XmlElement 

### ISSUE THREAD

**Issue by ali2236** [renggli/dart-xml#76]
Hi.
I was working on my xml widget builder And I found out that there is no getter to get the first `XmlElement` child. There is `firstChild` but that returns the first `XmlNode` which can be a comment and needs type casting.

Currently, getting the first element is tedious and not beginner friendly:
```dart
var child = body.children.whereType<XmlElement>().first;
```

In `xml 4.2.0` this can be done with much less code using the `getElement` function but there is no comments saying how to do it:
```dart
var child1 = body.getElement('*');
``` 

Also this feature should only work on `XmlDocument` and `XmlElement`, more importantly `XmlElement`.

My proposition is to add a getter like this:
```dart
extension on XmlElement {
  XmlElement get firstElementChild => children.firstWhere(
        (e) => e is XmlElement,
        orElse: () => null,
      );
}
```

**Comment by renggli** [comment]
Thanks for the idea, added it with 0c04ed1.
