### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by jpc-ae** [renggli/dart-xml#77]
The following line:

> To write back the parsed XML document simply call `toString()`, if you need more control `toXmlString(petty: true, indent: '\t')`:

has a typo where 'petty' should be 'pretty'.

To make it more readable, I might change the line to:
>  To write back the parsed XML document, simply call `toString()` (or `toXmlString({bool pretty, String indent, XmlEntityMapping entityMapping})` if you need more control):

**Comment by renggli** [comment]
Thank you. Feel free to create pull requests directly throug the web interface if you spot anything else.
