### ISSUE TITLE
Regression: preserve whitespace

### ISSUE THREAD

**Issue by rspilker** [renggli/dart-xml#78]
In version 3.7.0, it was possible to put newline characters in an `XmlText` node. Those newlines would be preserved in the output of the pretty printer.

In version 4.1.0, this is no longer the case.

I have to generate a document that has the following XSD declaration:
```xml
	<xs:simpleType name="pre-string">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
		</xs:restriction>
	</xs:simpleType>
```

Unfortunately, [I cannot upgrade to 4.1.0](https://github.com/TOPdesk/dart-junitreport).

I think that `XmlText` or `XmlElement` should have an additional attribute `preserveWhiteSpace` so the pretty printer can _not_ normalize those nodes.

**Comment by renggli** [comment]
Thank you for reporting. Whitespaces are tricky, particularly with pretty printing and/or without XSD infrastructure. If you want to preserve the whitespaces you should probably not pretty print or put the significant whitespaces into `cdata` sections.

Adding an attribute to elements about whitespaces seems strange, this should be at the meta-level. Though I am keeping this bug open to consider adding some more configuration options to the pretty printer itself (add callbacks to test if whitespaces should be preserved, if tags can be inlined, etc.)

**Comment by rspilker** [comment]
I did consider using a CDATA section, but I'm not certain that the consumers of my output will handle that correctly. 

I also understand your dillema. Especially because you would probably also need this information when parsing XML.

Currently, I get a 10 point penalty on the maintenance score on [pub.dav](https://pub.dev/packages/junitreport#-analysis-tab-) because I'm not on the latest available version of XML. Which I think is good, I want to always be on the latest version, especially because if a vulnerability is found on a previous version, I want to be able to update immediately. 

My problem is that I cannot update now, because of the uncertainty if my downstream consumers hande CDATA sections properly. That's why I hoped I would be able to get the previous behavior without using CDATA sections.

**Comment by renggli** [comment]
I could add an optional predicate to the pretty printer, were the pretty printer would ask you if it should preserve the whitespaces within an element or not? Like this you could control yourself if whitespaces should be touched or not. Would that be helpful?

**Comment by rspilker** [comment]
Perfect
