### ISSUE TITLE
the method 'parse' isn't defined for the type XmlDocument

### ISSUE THREAD

**Issue by Ohpizarro** [renggli/dart-xml#80]
final document = XmlDocument.parse(bookshelfXml);

**Comment by renggli** [comment]
This method is new in [version 4.2.0](https://github.com/renggli/dart-xml/blob/master/CHANGELOG.md#420).

**Comment by Ohpizarro** [comment]
flutter pub get

[webservicezofri] flutter pub get
Running "flutter pub get" in webservicezofri...                 
Because every version of flutter_test from sdk depends on xml 3.6.1 and webservicezofri depends on xml ^4.2.0, flutter_test from sdk is forbidden.

So, because webservicezofri depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because webservicezofri depends on flutter_test any from sdk, version solving failed.)
exit code 1

**Comment by renggli** [comment]
Please report this issue to `flutter_test` package then, I do not control what version of this library other packages depend on.

**Comment by Ohpizarro** [comment]
thanks for the library.

solved
1) flutter channel master
2) flutter upgrade
3) flutter channel stable
4) flutter upgrade
