### ISSUE TITLE
Add convenience method parseFromFile

### ISSUE THREAD

**Issue by bsutton** [renggli/dart-xml#81]
Rolled out your library for the first time and it took me a little while to realise that the library doesn't support directly parsing from a file.

This would be more convenient that having to load the file yourself.

I would suggest two options

Future<XmlDocument> Document.parseFromFile(filePath);

XmlDocument Document.parseFromFileSync(filePath);

The addition of these two methods would make the library far easier to use in what I imagine are the most common use cases.

**Comment by renggli** [comment]
The problem with such a function is that it makes the library depend on [dart:io](https://api.dart.dev/stable/2.8.4/dart-io/dart-io-library.html), which is not compatible with browser-based applications. As such, I prefer prefer to keep the library compatible with all Dart environments at the cost of requiring the user to have to write their own code to read the file.

**Comment by bsutton** [comment]
Maybe the halfway house is to include an example that reads from a file.

**Comment by renggli** [comment]
There are several:
https://github.com/renggli/dart-xml/blob/3591ed664e95b21d18774e63bead811eee653c72/example/xml_pos.dart#L53 https://github.com/renggli/dart-xml/blob/0615531dcb62c93e3fbe1d12719dd2f4f73bdb26/example/xml_grep.dart#L55 https://github.com/renggli/dart-xml/blob/0615531dcb62c93e3fbe1d12719dd2f4f73bdb26/example/xml_flatten.dart#L50

**Comment by renggli** [comment]
Agreed, an example in the tutorial and/or the method comments would probably be easier to find.

**Comment by bsutton** [comment]
I know you have laid the examples the way that pub.dev recommends but I
didn't  find the example page very useful as it didn't contain any actual
code snippets.

Now that I've found how the example layout works and where the code is it's
easy to find, but I didn't find this without your help.

I think reading from a file is such a fundamental operation that you should
have an example snippet on the readme page near the top or the example page
should actually contain some of the code for the examples or a link that
takes you directly to the sample code.

I really feel that users shouldn't have to go opening up dart files to find
out how an api works.
