### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by csacchetti** [renggli/dart-xml#82]
I try to get this package in pubspec.yaml but it return me an error. The error message is this:

"Because every version of flutter_test from sdk depends on xml 3.6.1 and podcast_exemple depends on xml ^4.2.0, flutter_test from sdk is forbidden.
So, because podcast_exemple depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because podcast_exemple depends on flutter_test any from sdk, version solving failed.)"

I've the last version of Flutter stable channel: 1.17.5

Can someone help me? Thanks

**Comment by renggli** [comment]
I do not control what version of the `xml` package other packages depend on, report the problem to `flutter_test` and/or `podcast_exemple`.
