### ISSUE TITLE
Setting to place attributes on new line

### ISSUE THREAD

**Issue by talamaska** [renggli/dart-xml#83]
I'm performing some automated change on the AndroidManifest, but noticed that after the edition, the attribute are now on a single line. I have set the setting pretty to true, tried the preserveWhitespace predicate but it is working only for things inside the tags, not on the attributes. Is there a way to do it?

**Comment by renggli** [comment]
Not out of the box, but you could create your own pretty printer by subclassing `XmlPrettyWriter` and subclassing `void writeAttributes(XmlHasAttributes node)` or `void visitAttribute(XmlAttribute node)`.

**Comment by talamaska** [comment]
@renggli Just to make sure, this new predicate works only on the top level elements but not on the children?

**Comment by renggli** [comment]
No, it should work on any attribute in the DOM, see the tests that apply it to children of the root node: [visitor_test.dart#L134](https://github.com/renggli/dart-xml/blob/7c82ce573594784c9bcfd7bf96acc0837fbfa0be/test/visitor_test.dart#L134). By adapting the predicate you can make it trigger only on specific elements, levels, etc.

**Comment by talamaska** [comment]
ok got it, it seems that when preserveWhitespace is set the indentAttribute stops working

**Comment by renggli** [comment]
Yeah, preserveWhitespace switches to non-pretty mode. It is kind of tricky to ident attributes, if elements are part of the natural textual flow. Probably the best solution would be if the parsing and printing back could preserve the exact alignment of attributes in elements?

**Comment by talamaska** [comment]
No, that's fine just add docs for it.
