### ISSUE TITLE
namespace URI mapping when parsing using streams

### ISSUE THREAD

**Issue by SteveAlexander** [renggli/dart-xml#84]
I'm making a streams-based parser for the XML that gets returned from WEBDAV servers. These tend to use namespaces a lot, and there's no guarantee how the response will map URIs to local names.

I was hoping that the stream parser would track namespace mappings, so that I could use them in `selectSubtreeEvents`, but it looks like I need to write application code to track this. Is that so, or did I miss something?

Thanks

**Comment by SteveAlexander** [comment]
Would a `selectSubtreeEventsWithContext` be useful?

Working on this, using the latest code in this repo... I think having a version of `selectSubtreeEvents` that provides context like `whereWithContext` would be helpful here. That way, I can select a subtree event based on the namespace URI, by walking up the parents looking for namespace declarations.

**Comment by SteveAlexander** [comment]
I've ended up using `mapWithContext` to map `XmlStartElementEvents` to my own subclass `XmlStartElementNSEvent`, which adds a namespaces lookup to the event. This can then be used in `selectSubtreeEvents` to select where the fully qualified name (i.e. URI and name) matches. It's not too bad — but would be nice to have processing streams with namespaces supported in the library somehow.

**Comment by SteveAlexander** [comment]
This is what I've ended up with:

```dart
class XmlStartElementNSEvent extends XmlStartElementEvent {
  final Map<String, String> namespaces;
  const XmlStartElementNSEvent(
    String name, List<XmlEventAttribute> attributes, bool isSelfClosing, this.namespaces
  ) : super(name, attributes, isSelfClosing);

  bool fullyQualifiedNameMatches(String uri, String name) {
    return name == localName && uri == namespaces[namespacePrefix];
  }
}

extension XmlWithNamespaceExtension on Stream<List<XmlEvent>> {
  Stream<List<XmlEvent>> addNamespacesToStartEvents() {
    return this.mapWithContext<XmlEvent>((context, event) {
      if (event is XmlStartElementEvent) {
        final Map<String, String> namespaces = {};
        for (final element in context) {
          for (final attr in element.attributes) {
            if (attr.name == 'xmlns') {
              if (!namespaces.containsKey(null)) {
                namespaces[null] = attr.value;
              }
            } else if (attr.namespacePrefix == 'xmlns' && !namespaces.containsKey(attr.localName)) {
              namespaces[attr.localName] = attr.value;
            }
          }
        }
        return XmlStartElementNSEvent(
          event.name, event.attributes, event.isSelfClosing, namespaces
        );
      }
      return event;
    });
  }
}
```

**Comment by renggli** [comment]
I've committed #85 that attempts to integrated some of the above code into the core library. If this looks fine to you, I'll try to add some more tests.

**Comment by SteveAlexander** [comment]
Thanks! The code works great for me in terms of selecting a subtree using namespaceUri. The example is much cleaner now.

```dart
    someData
      .transform(utf8.decoder)
      .toXmlEvents()
      .withNamespace()
      .selectSubtreeEvents((event) => event.namespaceUri == 'DAV:' && event.localName == 'response')
      .toXmlNodes()
      .flatten()
      .forEach((node) {
      // etc
     }
```

As far as I'm concerned, this particular issue can be closed.

Next, I'm looking for something to help with #85. I've put some rough code that works for me in a branch, if you'd like to take a look. I'll comment in that issue.

**Comment by renggli** [comment]
Sure, feel free to share the branch.

I have an alternate proposal that would make `withNamespace()` unnecessary and would also solve various other problems: Adding `parentEvent` reference to `XmlEvent` that can be populated with a `withParent()` stream transformation. This would allow to ...

- implement `namespaceUri` dynamically without an extra transformation step,
- replace `mapWithContext` and `whereWithContext` with standard Dart transformation, and
- possibly will also make it possible to solve #85 in a nice way.

**Comment by renggli** [comment]
I submitted c9731f0, which fixes point (1) and (2). Next will be (3) in #85.
