### ISSUE TITLE
XmlElement.namespaceUri is null when within subtree

### ISSUE THREAD

**Issue by SteveAlexander** [renggli/dart-xml#85]
I'm using the streams API, and I have selected a subtree using `selectSubtreeEvents`, and converted it to nodes using `toXmlNodes`.

The problem I'm encountering is that as I'm processing these subtree nodes, `node.name.namespaceUri` is `null`, even though there is a namespace prefix. I guess what I'd like to happen is for each subtree to have its parents' namespace URIs made available here, even when they are not re-declared in this subtree.

**Comment by SteveAlexander** [comment]
I've had a go at making something in https://github.com/renggli/dart-xml/pull/87

I can see there are a few different ways of doing this — e.g. separate subclasses of XmlName for when a namespaceUri is provided rather than being lazily looked up.

My goal here is to be able to write code like this:

```dart
    someData
      .transform(utf8.decoder)
      .toXmlEvents()
      .withNamespace()
      .selectSubtreeEvents((event) => event.namespaceUri == 'DAV:' && event.localName == 'response')
      .toXmlNodes()
      .flatten()
      .forEach((node) {
        if (node is XmlElement) {
          print('namespaceUri: ${node.name.namespaceUri}');
        }
      });
```

This is achieved through teaching `toXmlNodes()` that if namespaceUris are present, to add these to XmlNames.

As there are a lot of XmlName instances, I wonder if using a const constructor here makes sense?

**Comment by renggli** [comment]
The problem with the proposed change is that it breaks the mutability of `XmlNode`. Depending on mutations to the nodes the information can get stale or invalid.

**Comment by renggli** [comment]
I believe 4457e08 should solve the problem:

```dart 
someData
    .transform(utf8.decoder)
    .toXmlEvents()
    .withParentEvents()
     // lookup of namespaces anywhere in the stream
    .selectSubtreeEvents((event) => event.namespaceUri == 'http://...')
    .toXmlNodes()
    .flatten()
    // lookup of namespaces anywhere in the nodes
    .forEach((node) {
        if (node is XmlElement) {
          print('namespaceUri: ${node.name.namespaceUri}');
        }
      });
```

Some more deeper unit tests are still missing, but my smoke tests seem to pass.

**Comment by SteveAlexander** [comment]
Amazing! Thank you
