### ISSUE TITLE
Supporting other language .xml file?

### ISSUE THREAD

**Issue by winnie-chaintope** [renggli/dart-xml#86]
i get this error _**Unhandled Exception: Expected name**_ when i use xml file in other language
will this package support other language soon / future? thanks

```
<?xml version="1.1" encoding="UTF-8"?>
<電文情報 version="5.0">
      <生年月日>昭和２８年２月１日</生年月日>
      <性別>男</性別>
</電文情報>
```

**Comment by renggli** [comment]
Thank you for reporting, this is a bug I wasn't aware of.

**Comment by renggli** [comment]
Strangely the names you use are not allowed according to https://www.w3.org/TR/xml11/#NT-NameStartChar. Maybe that is a bug in the standard? I noticed some differences with https://en.wikipedia.org/wiki/QName, and added the missing character sets to the parser. Like this your example passes. I've also added it as a test. Please let me know if you encounter other problems.
