### ISSUE TITLE
Error: The method 'toXmlEvents' isn't defined for the class 'Stream<String>'. 

### ISSUE THREAD

**Issue by ikarelin** [renggli/dart-xml#88]
Error: The method 'toXmlEvents' isn't defined for the class 'Stream<String>'.
 - 'Stream' is from 'dart:async'.
Try correcting the name to the name of an existing method, or defining a method named 'toXmlEvents'.
      .toXmlEvents()
       ^^^^^^^^^^^

The code is from xml document page on pub.dev:

`final url = Uri.parse('http://ip-api.com/xml/');
  final request = await httpClient.getUrl(url);
  final response = await request.close();
  await response
      .transform(utf8.decoder)
      .toXmlEvents()
      .normalizeEvents()
      .flatten()
      .forEachEvent(onText: (event) => print(event.text));`

I believe the problem is with the latest dart version.

`dart --version
Dart SDK version: 2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "macos_x64"
`

**Comment by renggli** [comment]
Works for me, are you importing `import 'package:xml/xml_events.dart';`?

**Comment by ikarelin** [comment]
Yes. I believe the problem appeared with dart version 2.9.1/2.9.2
For me replacing 'toXmlEvents' with ' .transform(const XmlEventDecoder())' is working.

**Comment by renggli** [comment]
As I wrote, I cannot reproduce the problem with _Dart 2.9.2_ and neither _xml 4.4.1_ or _xml 4.5.0_. I get your exact error message if I don't import `package:xml/xml_events.dart`. Note that this is a different package than `package:xml/xml.dart`, see the first paragraph of https://github.com/renggli/dart-xml#streaming.

**Comment by ikarelin** [comment]
Removed and added again xml_events.dart import and it's working.
Thank You !!!
