### ISSUE TITLE
xml >=4.3.0 depends on meta ^1.2.0 and every version of flutter depends on meta 1.1.8

### ISSUE THREAD

**Issue by pjpsoft** [renggli/dart-xml#90]
I upgraded today to the latest stable:
 
Flutter 1.20.4 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (2 days ago) • 2020-09-14 15:32:52
-0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

and I get this error
Because xml >=4.3.0 depends on meta ^1.2.0 and every version of flutter from sdk depends on meta 1.1.8, xml >=4.3.0 is incompatible with flutter from sdk.

**Comment by renggli** [comment]
I published `xml 4.5.1` that is ok with an outdated version of meta.

**Comment by pjpsoft** [comment]
Merci
Pierre
