### ISSUE TITLE
Render a xml with xslt

### ISSUE THREAD

**Issue by giacomok** [renggli/dart-xml#91]
Is there a chance to render an xml file with xslt?

**Comment by renggli** [comment]
Sure, but I neither have a use-case for it nor the expertise. This could be an extension library, happy to provide support with this infrastructure present in this package.

**Comment by kiriruru** [comment]
Hi Lukas! I have many xslt use-cases and apply experience for SSR template engine (sites frontend). I migrate from php to dart but xslt for dart is not exists now :( I try using cli xsltproc, but this is stupid. IMHO, ffi for libxslt may stand is a great response. But I don't have experience with ffi. May be You known like decision for libxslt or example for ffi with libxml?

**Comment by renggli** [comment]
Creating FFI bindings for `libxslt` sounds like a great idea, but this is unrelated to this package and should probably be done separately. `libxslt` has its own XML parser and infrastructure.
