### ISSUE TITLE
XML File called and it can't  be read

### ISSUE THREAD

**Issue by wasimakram3** [renggli/dart-xml#94]
This is source code of main.dart. Getting   
Uncaught Unsupported operation: _Namespace
please reply soon

library example;

  import 'dart:convert';
  import 'dart:html';
  import 'package:modern_charts/modern_charts.dart';
  import 'dart:math';
  import 'package:xml/xml.dart';
  import 'dart:io' as filecall;
  //import 'dart:async';
  //import 'package:universal_io/io.dart' as filecall;
  import 'package:http/http.dart' as http;
  import 'package:xml2json/xml2json.dart';

  final random = Random();

  int rand(int min, int max) => random.nextInt(max - min) + min;

  Future<void> main() async {
    final file = new filecall.File('bookshelf.xml');
    final document3 = XmlDocument.parse(file.readAsStringSync());
    print(document3.toString());
  }

  Element createContainer() {
    var e = DivElement()
      ..style.height = '300px'
  //    ..style.width = '800px'
      ..style.maxWidth = '100%'
      ..style.marginBottom = '30px';
    document.body.append(e);
    return e;
  }

**Comment by renggli** [comment]
I don't think the error you are getting is related to this library. There is no such thing as `_Namespace` in this library.

The following minimal code works for me, add your changes one-by-one to see what breaks it:

```dart
import 'dart:io';
import 'package:xml/xml.dart';

void main()  {
  final file = File('bookshelf.xml');
  final document = XmlDocument.parse(file.readAsStringSync());
  print(document.toString());
}
```

**Comment by wasimakram3** [comment]
I'm using a web project in flutter. I have called the minimal code you given above, but the same error comes.  I have attached screen shots and source code
[sampleapp.zip](https://github.com/renggli/dart-xml/files/5353052/sampleapp.zip)


![flutter1](https://user-images.githubusercontent.com/72560946/95553029-5f14c400-0a2b-11eb-930c-e544a826facb.PNG)
![flutter2](https://user-images.githubusercontent.com/72560946/95553045-64720e80-0a2b-11eb-80c8-9151784587c5.PNG)

**Comment by renggli** [comment]
I don't think the 'dart:io' is supported on the web. You can confirm by just trying to print the textual content of the file?
