### ISSUE TITLE
Add a getter to get the XmlText of an XmlNode

### ISSUE THREAD

**Issue by tnc1997** [renggli/dart-xml#97]
Thank you very much for your work on this package @renggli.

I was wondering if it might be possible to add a method to conveniently get the `XmlText` of an `XmlNode`.

Currently it is possible to get the `XmlText` of an `XmlNode` via `singleWhere()`:

```dart
final text = element.children.singleWhere((node) => node is XmlText, orElse: () => null);
```

However with the introduction of null safety the code becomes more verbose:

```dart
XmlText? text;
for (var child in children) {
  if (child is XmlText) {
    text = child;
  }
}
```

I see that there is already a `text` getter inside the `XmlHasText` mixin, however this forwards onto the `innerText` getter which returns the concatenated text of this node and all its descendants. I would therefore like to propose the addition of something similar to the `getAttributeNode()` method inside the `XmlHasAttributes` mixin if possible:

```dart
XmlText? get textNode {
  for (final node in children) {
    if (node is XmlText) {
      return node;
    }
  }
  return null;
}
```

**Comment by renggli** [comment]
I am afraid that this is not generally reusable. There are different types of text nodes, and a single text nodes is also a rather specific case. What about you create an extension method yourself?

```dart
extension MyTextExtension on XmlNode {
  XmlText? get mySpecialTextNode => ...
}
```

**Comment by tnc1997** [comment]
Sounds good to me, I will use an extension method instead. Thank you for considering the proposal!
